### PR TITLE
Fix engine-withdrawals hive tests 

### PR DESCRIPTION
**Pull request by jochem-brouwer**

### CODE REVIEW

**Comment by jochem-brouwer** [comment]
After 6cd6959: 

```
INFO[01-26|12:08:12] building image                           image=hive/hiveproxy nocache=false pull=false
INFO[01-26|12:08:12] building 1 clients... 
INFO[01-26|12:08:12] building image                           image=hive/clients/ethereumjs:latest dir=clients/ethereumjs nocache=false pull=false
INFO[01-26|12:08:37] building 1 simulators... 
INFO[01-26|12:08:37] building image                           image=hive/simulators/ethereum/engine:latest dir=simulators/ethereum/engine nocache=false pull=false
INFO[01-26|12:08:37] running simulation: ethereum/engine 
INFO[01-26|12:08:37] hiveproxy started                        container=53627669b2ae addr=172.17.0.2:8081
INFO[01-26|12:08:37] API: suite started                       suite=0 name=engine-withdrawals
INFO[01-26|12:08:37] API: test started                        suite=0 test=1 name="Withdrawals Fork On Genesis (ethereumjs)"
INFO[01-26|12:08:41] API: client ethereumjs started           suite=0 test=1 container=d021bc03
INFO[01-26|12:08:47] API: test ended                          suite=0 test=1 pass=true
INFO[01-26|12:08:47] API: test started                        suite=0 test=2 name="Withdrawals Fork on Block 1 (ethereumjs)"
INFO[01-26|12:08:52] API: client ethereumjs started           suite=0 test=2 container=4fdaee5d
INFO[01-26|12:08:56] API: test ended                          suite=0 test=2 pass=true
INFO[01-26|12:08:56] API: test started                        suite=0 test=3 name="Withdrawals Fork on Block 2 (ethereumjs)"
INFO[01-26|12:09:00] API: client ethereumjs started           suite=0 test=3 container=2d652d70
INFO[01-26|12:09:05] API: test ended                          suite=0 test=3 pass=true
INFO[01-26|12:09:05] API: test started                        suite=0 test=4 name="Withdrawals Fork on Block 3 (ethereumjs)"
INFO[01-26|12:09:09] API: client ethereumjs started           suite=0 test=4 container=07ed3e3a
INFO[01-26|12:09:15] API: test ended                          suite=0 test=4 pass=true
INFO[01-26|12:09:15] API: test started                        suite=0 test=5 name="Withdraw to a single account (ethereumjs)"
INFO[01-26|12:09:20] API: client ethereumjs started           suite=0 test=5 container=02005633
INFO[01-26|12:09:24] API: test ended                          suite=0 test=5 pass=true
INFO[01-26|12:09:24] API: test started                        suite=0 test=6 name="Withdraw to two accounts (ethereumjs)"
INFO[01-26|12:09:28] API: client ethereumjs started           suite=0 test=6 container=ddb80fbf
INFO[01-26|12:09:32] API: test ended                          suite=0 test=6 pass=true
INFO[01-26|12:09:32] API: test started                        suite=0 test=7 name="Withdraw many accounts (ethereumjs)"
INFO[01-26|12:09:37] API: client ethereumjs started           suite=0 test=7 container=7f0a1dad
INFO[01-26|12:13:01] API: test ended                          suite=0 test=7 pass=true
INFO[01-26|12:13:01] API: test started                        suite=0 test=8 name="Withdraw zero amount (ethereumjs)"
INFO[01-26|12:13:05] API: client ethereumjs started           suite=0 test=8 container=95b50cc1
INFO[01-26|12:13:09] API: test ended                          suite=0 test=8 pass=true
INFO[01-26|12:13:09] API: test started                        suite=0 test=9 name="Empty Withdrawals (ethereumjs)"
INFO[01-26|12:13:13] API: client ethereumjs started           suite=0 test=9 container=1e872745
INFO[01-26|12:13:17] API: test ended                          suite=0 test=9 pass=true
INFO[01-26|12:13:17] API: test started                        suite=0 test=10 name="Sync after 2 blocks - Withdrawals on Block 1 - Single Withdrawal Account - No Transactions (ethereumjs)"
INFO[01-26|12:13:21] API: client ethereumjs started           suite=0 test=10 container=98e08100
INFO[01-26|12:13:24] API: container IP requested              network=bridge container=98e08100 ip=172.17.0.4
INFO[01-26|12:13:29] API: client ethereumjs started           suite=0 test=10 container=3bfcdfa2
INFO[01-26|12:13:40] API: test ended                          suite=0 test=10 pass=true
INFO[01-26|12:13:40] API: test started                        suite=0 test=11 name="Sync after 2 blocks - Withdrawals on Block 1 - Single Withdrawal Account (ethereumjs)"
INFO[01-26|12:13:44] API: client ethereumjs started           suite=0 test=11 container=d55a5ef8
INFO[01-26|12:13:48] API: container IP requested              network=bridge container=d55a5ef8 ip=172.17.0.4
INFO[01-26|12:13:52] API: client ethereumjs started           suite=0 test=11 container=2b413581
INFO[01-26|12:14:03] API: test ended                          suite=0 test=11 pass=true
INFO[01-26|12:14:03] API: test started                        suite=0 test=12 name="Sync after 2 blocks - Withdrawals on Genesis - Single Withdrawal Account (ethereumjs)"
INFO[01-26|12:14:07] API: client ethereumjs started           suite=0 test=12 container=eaaaf159
INFO[01-26|12:14:11] API: container IP requested              network=bridge container=eaaaf159 ip=172.17.0.4
INFO[01-26|12:14:15] API: client ethereumjs started           suite=0 test=12 container=7eee58a8
INFO[01-26|12:14:26] API: test ended                          suite=0 test=12 pass=true
INFO[01-26|12:14:26] API: test started                        suite=0 test=13 name="Sync after 2 blocks - Withdrawals on Block 2 - Multiple Withdrawal Accounts - No Transactions (ethereumjs)"
INFO[01-26|12:14:30] API: client ethereumjs started           suite=0 test=13 container=353f2d65
INFO[01-26|12:14:35] API: container IP requested              network=bridge container=353f2d65 ip=172.17.0.4
INFO[01-26|12:14:39] API: client ethereumjs started           suite=0 test=13 container=65793aa0
INFO[01-26|12:14:50] API: test ended                          suite=0 test=13 pass=true
INFO[01-26|12:14:50] API: test started                        suite=0 test=14 name="Sync after 2 blocks - Withdrawals on Block 2 - Multiple Withdrawal Accounts (ethereumjs)"
INFO[01-26|12:14:54] API: client ethereumjs started           suite=0 test=14 container=4c56ed98
INFO[01-26|12:14:59] API: container IP requested              network=bridge container=4c56ed98 ip=172.17.0.4
INFO[01-26|12:15:03] API: client ethereumjs started           suite=0 test=14 container=a4704bcb
INFO[01-26|12:15:14] API: test ended                          suite=0 test=14 pass=true
INFO[01-26|12:15:14] API: test started                        suite=0 test=15 name="Sync after 128 blocks - Withdrawals on Block 2 - Multiple Withdrawal Accounts (ethereumjs)"
INFO[01-26|12:15:19] API: client ethereumjs started           suite=0 test=15 container=f549a544
INFO[01-26|12:18:06] API: container IP requested              network=bridge container=f549a544 ip=172.17.0.4
INFO[01-26|12:18:11] API: client ethereumjs started           suite=0 test=15 container=ee4a398d
INFO[01-26|12:20:20] API: test ended                          suite=0 test=15 pass=false
INFO[01-26|12:20:20] API: test started                        suite=0 test=16 name="Withdrawals Fork on Block 1 - 1 Block Re-Org (ethereumjs)"
INFO[01-26|12:20:24] API: client ethereumjs started           suite=0 test=16 container=6c0487c1
INFO[01-26|12:20:26] API: container IP requested              network=bridge container=6c0487c1 ip=172.17.0.4
INFO[01-26|12:20:30] API: client ethereumjs started           suite=0 test=16 container=448aca98
INFO[01-26|12:21:35] API: test ended                          suite=0 test=16 pass=false
INFO[01-26|12:21:35] API: test started                        suite=0 test=17 name="Withdrawals Fork on Block 1 - 8 Block Re-Org NewPayload (ethereumjs)"
INFO[01-26|12:21:39] API: client ethereumjs started           suite=0 test=17 container=d54c5975
INFO[01-26|12:21:41] API: container IP requested              network=bridge container=d54c5975 ip=172.17.0.4
INFO[01-26|12:21:45] API: client ethereumjs started           suite=0 test=17 container=eb7125b6
INFO[01-26|12:22:50] API: test ended                          suite=0 test=17 pass=false
INFO[01-26|12:22:50] API: test started                        suite=0 test=18 name="Withdrawals Fork on Block 1 - 8 Block Re-Org, Sync (ethereumjs)"
INFO[01-26|12:22:54] API: client ethereumjs started           suite=0 test=18 container=5c1c938a
INFO[01-26|12:22:56] API: container IP requested              network=bridge container=5c1c938a ip=172.17.0.4
INFO[01-26|12:23:00] API: client ethereumjs started           suite=0 test=18 container=45c9bc4e
INFO[01-26|12:24:05] API: test ended                          suite=0 test=18 pass=false
INFO[01-26|12:24:05] API: test started                        suite=0 test=19 name="Withdrawals Fork on Block 8 - 10 Block Re-Org NewPayload (ethereumjs)"
INFO[01-26|12:24:09] API: client ethereumjs started           suite=0 test=19 container=1680d49f
INFO[01-26|12:24:11] API: container IP requested              network=bridge container=1680d49f ip=172.17.0.4
INFO[01-26|12:24:15] API: client ethereumjs started           suite=0 test=19 container=f09a8a4d
INFO[01-26|12:25:20] API: test ended                          suite=0 test=19 pass=false
INFO[01-26|12:25:20] API: test started                        suite=0 test=20 name="Withdrawals Fork on Block 8 - 10 Block Re-Org Sync (ethereumjs)"
INFO[01-26|12:25:24] API: client ethereumjs started           suite=0 test=20 container=2c2ccd55
INFO[01-26|12:25:26] API: container IP requested              network=bridge container=2c2ccd55 ip=172.17.0.4
INFO[01-26|12:25:30] API: client ethereumjs started           suite=0 test=20 container=e4ac7ce5
INFO[01-26|12:26:35] API: test ended                          suite=0 test=20 pass=false
INFO[01-26|12:26:35] API: test started                        suite=0 test=21 name="Withdrawals Fork on Canonical Block 8 / Side Block 7 - 10 Block Re-Org (ethereumjs)"
INFO[01-26|12:26:39] API: client ethereumjs started           suite=0 test=21 container=8522157a
INFO[01-26|12:26:41] API: container IP requested              network=bridge container=8522157a ip=172.17.0.4
INFO[01-26|12:26:45] API: client ethereumjs started           suite=0 test=21 container=dd3ced47
INFO[01-26|12:27:50] API: test ended                          suite=0 test=21 pass=false
INFO[01-26|12:27:50] API: test started                        suite=0 test=22 name="Withdrawals Fork on Canonical Block 8 / Side Block 7 - 10 Block Re-Org Sync (ethereumjs)"
INFO[01-26|12:27:54] API: client ethereumjs started           suite=0 test=22 container=5192d70f
INFO[01-26|12:27:56] API: container IP requested              network=bridge container=5192d70f ip=172.17.0.4
INFO[01-26|12:28:00] API: client ethereumjs started           suite=0 test=22 container=fbe9b632
INFO[01-26|12:29:05] API: test ended                          suite=0 test=22 pass=false
INFO[01-26|12:29:05] API: test started                        suite=0 test=23 name="Withdrawals Fork on Canonical Block 8 / Side Block 9 - 10 Block Re-Org (ethereumjs)"
INFO[01-26|12:29:09] API: client ethereumjs started           suite=0 test=23 container=0453373d
INFO[01-26|12:29:11] API: container IP requested              network=bridge container=0453373d ip=172.17.0.4
INFO[01-26|12:29:15] API: client ethereumjs started           suite=0 test=23 container=3c9ac98d
INFO[01-26|12:30:20] API: test ended                          suite=0 test=23 pass=false
INFO[01-26|12:30:20] API: test started                        suite=0 test=24 name="Withdrawals Fork on Canonical Block 8 / Side Block 9 - 10 Block Re-Org Sync (ethereumjs)"
INFO[01-26|12:30:24] API: client ethereumjs started           suite=0 test=24 container=7209fc93
INFO[01-26|12:30:26] API: container IP requested              network=bridge container=7209fc93 ip=172.17.0.4
INFO[01-26|12:30:30] API: client ethereumjs started           suite=0 test=24 container=e7c3bffe
INFO[01-26|12:31:35] API: test ended                          suite=0 test=24 pass=false
INFO[01-26|12:31:35] API: test started                        suite=0 test=25 name="Max Initcode Size (ethereumjs)"
INFO[01-26|12:31:39] API: client ethereumjs started           suite=0 test=25 container=cd7edaa7
INFO[01-26|12:31:45] API: test ended                          suite=0 test=25 pass=true
INFO[01-26|12:31:45] API: suite ended                         suite=0
INFO[01-26|12:31:46] simulation ethereum/engine finished      suites=1 tests=25 failed=10
10 tests failed
exit status 1
```

**Comment by holgerd77** [comment]
Hi Jochem, I would like to get the existing changes from here into the next release, can we eventually merge and you continue in a follow up PR? 🤔

**Comment by jochem-brouwer** [comment]
Hive tests have uncovered some bugs with our client startup. These are not yet fixed. However, this PR fixes some of these startup problems.

**Comment by g11tech** [comment]
closing as the diff here seems to be gotten incorporated in other PR fixes

**Pull request closed without merging**
