### PR TITLE
Final Breaking Releases

### PR DESCRIPTION
**Pull request by holgerd77**
Finally. 🎉

This PR updates the CHANGELOG files from all libraries and bumps the version numbers to final versions. All libraries already included and ready for review, maybe be a bit loose on change requests and if you do please directly update on the branch (maybe with announcing before publicly so updates do not interfere with each other).

Some noteworthy things:

- This time I also updated the `package-lock.json` 😋
- I switched back version ranges for our internal dependencies to our normal `^` range from being fixed for the time of Beta and RC releases
- Also included a client release as the final "Merge ready one", only did a bugfix version bump since not so much happened: nevertheless 🙂 
- On the client I actually switched from `^` to fixed versions for internal dependencies, guess this will make our lives easier in the future by not always needing to fear to break things in the client with bugfix or minor releases on the other libraries

Ok. Thanks everyone for making this happen!!! 🤩 💯 ❤️

### CODE REVIEW

**Review by g11tech — APPROVED** [review]
looks awesome!

**Review by jochem-brouwer — APPROVED** [review]
LGTM :tada:

**Review by acolytec3 — APPROVED** [review]
LGTM.  To infinity and beyond!

**Review by paulmillr — APPROVED** [review]

**Review by gabrocheleau — APPROVED** [review]

**Review by ScottyPoi — APPROVED** [review]

**Comment by holgerd77** [comment]
The most approved PR in the history of EthereumJS! 🎉 😋

Thanks a lot guys, awesome work and impressive patience from all of you!!! 💯 ❤️

**Comment by holgerd77** [comment]
Just published the following releases on npm:

- `@ethereumjs/rlp` [v4.0.0](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Frlp%404.0.0)
- `@ethereumjs/util` [v8.0.0](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Futil%408.0.0)
- `@ethereumjs/common` [v3.0.0](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fcommon%403.0.0)
- `@ethereumjs/trie` [v5.0.0](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Ftrie%405.0.0)
- `@ethereumjs/devp2p` [v5.0.0](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fdevp2p%405.0.0)
- `@ethereumjs/tx` [v4.0.0](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Ftx%404.0.0)
- `@ethereumjs/block` [v4.0.0](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fblock%404.0.0)
- `@ethereumjs/ethash` [v2.0.0](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fethash%402.0.0)
- `@ethereumjs/blockchain` [v6.0.0](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fblockchain%406.0.0)
- `@ethereumjs/statemanager` [v1.0.0](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fstatemanager%401.0.0)
- `@ethereumjs/evm` [v1.0.0](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fevm%401.0.0)
- `@ethereumjs/vm` [v6.0.0](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fvm%406.0.0)
- `@ethereumjs/client` [v0.6.3](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fclient%400.6.3)

**Pull request merged**
