### PR TITLE
modify rpcStataManager getAccount

### PR DESCRIPTION
**Pull request by rodrigoherrerai**
When getting an account from the provider that has never been touched, the returned codeHash is not keccak(""), but just empty bytes (0...0).  Therefore, the getAccount function will not return "undefined" but an account with empty bytes. 

This creates a problem in some edge cases. For example, when forking a network and creating a contract within a contract, the evm will revert with collision error, due to this implementation.

### CODE REVIEW

**Comment by scorbajio** [comment]
This looks good to me. Would be useful to capture some data and add a unit test.

**Comment by acolytec3** [comment]
> Would be useful to capture some data and add a unit test.

This should already be covered in the existing tests.  I've also updated our `mockProvider` to return a response that mirrors the Infura API response to `getProof` for non-existent accounts.

**Comment by acolytec3** [comment]
Have also updated the check of the `codeHash` field to compare the underlying bytes instead of `.every(...` notation per some internal discussion.

**Review by acolytec3 — APPROVED** [review]
LGTM!  Thanks for the PR.

**Pull request merged**
