### PR TITLE
New MPT Release v4.2.1

### PR DESCRIPTION
**Pull request by holgerd77**

### CODE REVIEW

**Comment by holgerd77** [comment]
Oh, interesting.

All failing with:

```shell
Run npm i
npm ERR! code ETARGET
npm ERR! notarget No matching version found for merkle-patricia-tree@^4.2.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-08-17T11_13_18_526Z-debug.log
```

**Comment by acolytec3** [comment]
This is an issue related to `workspaces`.  I get the same result when running locally.  If I'm reading the logs correctly, I think we have to build the `trie` package first but running something like `npm run build --workspace=@ethereumjs/trie` results in a `no workspaces found` error.

**Comment by ryanio** [comment]
@holgerd77 I don't believe you committed an updated package-lock so that's my first thought, I'll give that a try here with an added commit.

@acolytec3 the packages have a `tsconfig.prod.ts` with project references that will build those first. The package name for the trie is still `merkle-patricia-tree` not `@ethereumjs/trie` so that's the issue you're experiencing.

**Review by ryanio — APPROVED** [review]
lgtm, thanks for putting together the release!

**Comment by holgerd77** [comment]
@ryanio ah, thanks, didn't know that there is now a strict requirement to rebuild and commit `package-lock.json` on release PRs. Good to know! 😄

**Comment by holgerd77** [comment]
Cannot do the release atm since the `npm run build` command is not working properly, this becomes more clear on release since there is an `npm run clean` run before which deletes the `dist` and `dist.browser` folders.

Before - when I didn't run `npm i` in the root folder, it didn't build any of those folders. I then ran `npm i`, now at least the `dist` folder is build but not the `dist.browser` folder.

Leave this for now since I guess @ryanio or eventually also @acolytec3 might have a more spotty eye here to see what's wrong. 😄

**Comment by holgerd77** [comment]
Update: this is working (at least for me) for another package (tested for `common`, so 1) clean 2) build).

Did a test with renaming the `trie` directory to `merkle-patricia-tree` (this was the first thing which came to my mind), but didn't work.

**Comment by ryanio** [comment]
This should be solved by #1410 by removing `*.tsbuildinfo` as part of `clean`, could you give it another try once that is merged into master?

**Comment by holgerd77** [comment]
Just published this on npm as [v4.2.1](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/merkle-patricia-tree%404.2.1).

**Pull request merged**
