### PR TITLE
VM: stateManager -> add modifyAccountFields method

### PR DESCRIPTION
**Pull request by emersonmacro**
Addresses #731.

This was my first time working with `stateManager` and I was learning as I went, so any feedback, suggestions, or critique are welcomed.

There was one part of the original issue that I wasn't able to figure out: `The method should probably throw if account doesn't exist.`. I attempted that but couldn't get it to work, and after some digging, it looks like if the account doesn't exist, a new one will be created, so an account always exists when `getAccount` is called. Is there something I'm not understanding?

### CODE REVIEW

**Comment by acolytec3** [comment]
Per [previous comments](https://github.com/ethereumjs/ethereumjs-monorepo/issues/1226#issuecomment-826785596), `getAccount` creates a new account if it doesn't already exist in the `stateManager` as you noted so I think the question here is, should `getAccount` create a new account or not?  The docs currently state `Returns an empty account if the account does not exist` so that seems pretty clear to me that it shouldn't throw unless we're going to change the design, which would be a breaking change here since it would change the behavior of the function.  @ryanio @jochem-brouwer thoughts?

**Review by acolytec3 — DISMISSED** [review]
This looks great.  I added one additional test to prove out the fact that modifying a non-existent account will first create an empty one and then update its values accordingly.

**Comment by jochem-brouwer** [comment]
I don't know the reasoning behind throwing if the account does not exist. I'd say it makes much sense, and is consistent, to just take the empty account and then modify these fields.

**Review by jochem-brouwer — DISMISSED** [review]
This looks good to me!

**Comment by ryanio** [comment]
looks great. is there anywhere we can use this new method within our own internal VM then? or is it just a convenience helper for external use?

**Comment by emersonmacro** [comment]
@ryanio Ah, yes I think there are some spots internally where this new method could be used. Should I include that as part of this PR or tackle separately?

**Comment by ryanio** [comment]
I say let's include it as part of this PR, so that the changes are contained together nicely.

**Comment by emersonmacro** [comment]
PR updated with some usage changes

**Review by ryanio — APPROVED** [review]
looks really great!

**Pull request merged**
