### PR TITLE
client: Miscellaneous tx related fixes for eth methods 

### PR DESCRIPTION
**Pull request by g11tech**
- extend RpcTx, 
- blockOpt optional in estimateGas, 
- improved tx fields validation

some eth tx method fixes extracted from shandong
- https://github.com/ethereumjs/ethereumjs-monorepo/pull/2316

### CODE REVIEW

**Comment by acolytec3** [comment]
This looks good as far as it goes.  I've spent the last hour trying to figure out how to run a test for a london block without success, but it would be good to add those tests to verify things work right for Typed Transactions.  Will try to work on it some more and see if I can't get one that's valid.

**Comment by holgerd77** [comment]
Have re-labelled to "WIP" to reflect the latest comment, @acolytec3 please switch back to "Ready for review/merge" or something when you are done with the tests.

**Comment by acolytec3** [comment]
Finally got my new tests working.  We'll see if this makes code coverage happy and will merge if so.

**Review by acolytec3 — APPROVED** [review]
LGTM now that coverage is up!

**Pull request merged**
