### PR TITLE
block: point difficulty tests to ethereum-tests

### LINKED ISSUE #1557: Block difficulty tests
Currently we use edited difficulty test files for the block package to test the difficulty. This decreases coverage somewhat and might also not be up-to-date. We need to: 

- Read tests from ethereum/tests instead of copying the JSON files
- Read the entire JSON file. Currently it seems that we do not test for uncles (at least on ArrowGlacier)

### PR DESCRIPTION
**Pull request by acolytec3**
Fixes #1557 

This points the block difficulty tests to the correct tests in the `ethereum-tests` submodule and addresses the failure where some of the difficulty tests were failing due to the unclesHash changing from the `KECCACK256_RLP_ARRAY` to `0x00` (functionally equivalent for purposes of our test but causing it to fail since 0x00 isn't technically a valid RLP hash.

### CODE REVIEW

**Comment by acolytec3** [comment]
@holgerd77 @jochem-brouwer Hold off on review.  Looks like my local version of Ethereum-Tests was different than what the CI has for some reason though I thought I had updated correctly so will need to fix.

**Comment by holgerd77** [comment]
Ok. 🙂

**Comment by acolytec3** [comment]
@holgerd77 @jochem-brouwer Okay, fixed my local and it's all passing with (hopefully) the correct ethereum-tests directory structure.  One thing to note is I left the Arrow Glacier test data in the `block/test/testdata` folder as that set of tests doesn't exist in V10.0 of the Ethereum-Tests repo.

**Review by ryanio — APPROVED** [review]
lgtm!

**Pull request merged**
