### PR TITLE
Rename consensusFormatValidationFlag

### PR DESCRIPTION
**Pull request by acolytec3**
- Renames `consensusFormatValidation` to `skipConsensusFormatValidation` to match similar flags in `blockchain` and defaults this option to false.  
- Removes a couple of troublesome Kovan tests that would need to be removed with #2206

### CODE REVIEW

**Review by holgerd77 — APPROVED** [review]
LGTM

**Comment by holgerd77** [comment]
Ah, short nit: can you please update the header description that you didn't remove the Kovan tests along this PR (just delete is sufficient)?

**Comment by acolytec3** [comment]
I [did remove](https://github.com/ethereumjs/ethereumjs-monorepo/pull/2209/commits/afc3b552c07d7e1c9653b085851dccf00e37da5d) them though.  I'm not sure why they aren't showing up in the `Files Changed` section of the PR.  :thinking:

**Comment by holgerd77** [comment]
> I [did remove](https://github.com/ethereumjs/ethereumjs-monorepo/pull/2209/commits/afc3b552c07d7e1c9653b085851dccf00e37da5d) them though. I'm not sure why they aren't showing up in the `Files Changed` section of the PR. 🤔

Ah, these tests were already removed in the Kovan PR #2206 🙂 .

**Comment by holgerd77** [comment]
(maybe not do something like this before the related PR is merged, might also lead to somewhat dangerous situations (so, not dramatically dangerous, but just some file/update conflicts))

**Pull request merged**
