### PR TITLE
Monorepo: Develop -> Master - Breaking Release Transition PR

### PR DESCRIPTION
**Pull request by holgerd77**
Part of #1914, final execution on #1717

This is the PR to make the `develop` branch - where all work for the `v6` release series has been undertaken - will be merged into the `master` branch. With the merge of this branch there will be a transition to the `v6` series becoming the new work state.

All eventually necessary `v5` work will/should from now on be done towards the new [v5-maintenance](https://github.com/ethereumjs/ethereumjs-monorepo/tree/v5-maintenance) branch, branched off after the final round of v5 releases done in #1927 (and some follow-up work in #1929, #1931 and #1932).

Still open feature PRs towards `develop` should be re-applied/re-targeted towards `master` (likely via cherry-picking) after this PR has been merged.

Woohoo. 🙏 🎉

Thanks everyone for the great work being done here! ❤️

We are a bit late on schedule, so PR will be merged after 1-2 reviews/approvals.

### CODE REVIEW

**Comment by holgerd77** [comment]
Ok, this was an easy fix 🙂, so `eslint-plugin-typestrict` (from Kris, some former EthereumJS contributor 😋) jumped from `eslint-plugin` v4 to v5 as a peer dependency on the `1.0.3` -> `1.04` [version bump](https://github.com/krzkaczor/TypeStrict/commit/f62acad3b6eb02153c22e05cffabb6374f7e893e), and this caused the resolution problems on our side.

We definitely not want to align and update ESLint in this stage of the process, so I just fixed our `eslint-plugin-typescript` version to `1.0.3` and this solved the problem.

So this is now open for review. 🙂 


I will also deactivate the `e2e-hardhat` testrun for now for `master` for the first weeks or so of the transition, this will likely take some time to get fixed (on the Hardhat side).

**Comment by holgerd77** [comment]
Ah, and another question: there is now a `bigint-crypto-utils` dependency added as a main dependency to the root `package.json` file relatively recently.

Is this intended or is this some kind of forgotten left-over from the BigInt transition days? 🤔

No blocker for this PR though in any way, this can in doubt be fixed in a follow-up PR!

**Comment by acolytec3** [comment]
> Ah, and another question: there is now a `bigint-crypto-utils` dependency added as a main dependency to the root `package.json` file relatively recently.
> 
> Is this intended or is this some kind of forgotten left-over from the BigInt transition days? thinking
> 
> No blocker for this PR though in any way, this can in doubt be fixed in a follow-up PR!

I believe @ryanio added it for `ethash` when we migrated to `bigints`.  It's used [here](https://github.com/ethereumjs/ethereumjs-monorepo/blob/97554f2d165171c3c0ee382e289ed831891a5999/packages/ethash/src/util.ts#L1) for the 'Miller-Rabin' stuff.

**Comment by holgerd77** [comment]
> I believe @ryanio added it for `ethash` when we migrated to `bigints`. It's used [here](https://github.com/ethereumjs/ethereumjs-monorepo/blob/97554f2d165171c3c0ee382e289ed831891a5999/packages/ethash/src/util.ts#L1) for the 'Miller-Rabin' stuff.

And was it an intentional decision to add to the root `package.json` file? 🤔 ("Then we have it in doubt for the other libraries")?? Or did it just sneak in (for now I would assume the latter)?

Anyhow: again, up for a follow up PR in doubt.

(@acolytec3 if this looks fine for you can you give an approval?)

**Comment by acolytec3** [comment]
> > I believe @ryanio added it for `ethash` when we migrated to `bigints`. It's used [here](https://github.com/ethereumjs/ethereumjs-monorepo/blob/97554f2d165171c3c0ee382e289ed831891a5999/packages/ethash/src/util.ts#L1) for the 'Miller-Rabin' stuff.
> 
> And was it an intentional decision to add to the root `package.json` file? thinking ("Then we have it in doubt for the other libraries")?? Or did it just sneak in (for now I would assume the latter)?
> 
> Anyhow: again, up for a follow up PR in doubt.
> 
> (@acolytec3 if this looks fine for you can you give an approval?)

I think you can safely remove it.  It's also in the `ethash` package.json so must have just sneaked in some errant PR over time.

**Comment by holgerd77** [comment]
> I think you can safely remove it. It's also in the `ethash` package.json so must have just sneaked in some errant PR over time.

Ok, will do in one of the follow-up PRs.

**Review by acolytec3 — APPROVED** [review]
LGTM!  Two things for a follow-up PR
1) Remove `bigint-crypto-util` from root package.json
2) Fix `common` memory leak in eip-3074 test script

**Review by g11tech — APPROVED** [review]
:rocket:

**Pull request merged**
