### PR TITLE
VM: Update ethereum-tests to v8.0.4 (2021-04-27, post fork tests)

### PR DESCRIPTION
**Pull request by holgerd77**
This PR updates the `ethereum-tests` submodule to [v8.0.4](https://github.com/ethereum/tests/releases/tag/8.0.4).

### CODE REVIEW

**Comment by holgerd77** [comment]
Breaking tests:

`vm-state (Instanbul)`:

```shell
2021-04-27T07:50:38.0585502Z # file: randomStatetest649 test: randomStatetest649_d0g0v0_Istanbul
2021-04-27T07:50:38.0586157Z ok 12187 correct genesis RLP
2021-04-27T07:50:38.0597795Z ok 12188 correct pre stateRoot
2021-04-27T07:50:38.1054392Z Error: invalid receiptTrie
2021-04-27T07:50:38.1056218Z     at VM.runBlock (/home/runner/work/ethereumjs-monorepo/ethereumjs-monorepo/packages/vm/lib/runBlock.ts:162:13)
2021-04-27T07:50:38.1057894Z     at /home/runner/work/ethereumjs-monorepo/ethereumjs-monorepo/packages/vm/lib/runBlockchain.ts:37:9
2021-04-27T07:50:38.1059494Z     at /home/runner/work/ethereumjs-monorepo/ethereumjs-monorepo/packages/blockchain/src/index.ts:1244:13
2021-04-27T07:50:38.1061210Z     at Blockchain.runWithLock (/home/runner/work/ethereumjs-monorepo/ethereumjs-monorepo/packages/blockchain/src/index.ts:410:21)
2021-04-27T07:50:38.1063064Z     at Blockchain.initAndLock (/home/runner/work/ethereumjs-monorepo/ethereumjs-monorepo/packages/blockchain/src/index.ts:397:12)
2021-04-27T07:50:38.1065656Z     at Blockchain._iterator (/home/runner/work/ethereumjs-monorepo/ethereumjs-monorepo/packages/blockchain/src/index.ts:1221:12)
2021-04-27T07:50:38.1067618Z     at VM.runBlockchain (/home/runner/work/ethereumjs-monorepo/ethereumjs-monorepo/packages/vm/lib/runBlockchain.ts:18:10)
2021-04-27T07:50:38.1070521Z     at runBlockchainTest (/home/runner/work/ethereumjs-monorepo/ethereumjs-monorepo/packages/vm/tests/BlockchainTestsRunner.ts:129:7)
2021-04-27T07:50:38.1072271Z     at /home/runner/work/ethereumjs-monorepo/ethereumjs-monorepo/packages/vm/tests/tester.ts:172:19
2021-04-27T07:50:38.1073900Z     at fileCallback (/home/runner/work/ethereumjs-monorepo/ethereumjs-monorepo/packages/vm/tests/testLoader.ts:60:11)
2021-04-27T07:50:38.1075090Z not ok 12189 Error: invalid receiptTrie
2021-04-27T07:50:38.1075814Z   ---
2021-04-27T07:50:38.1076386Z     operator: fail
2021-04-27T07:50:38.1077952Z     at: handleError (/home/runner/work/ethereumjs-monorepo/ethereumjs-monorepo/packages/vm/tests/BlockchainTestsRunner.ts:90:9)
2021-04-27T07:50:38.1081167Z     stack: |-
2021-04-27T07:50:38.1087115Z       Error: Error: invalid receiptTrie
2021-04-27T07:50:38.1088353Z           at Test.assert [as _assert] (/home/runner/work/ethereumjs-monorepo/ethereumjs-monorepo/node_modules/tape/lib/test.js:228:54)
2021-04-27T07:50:38.1090152Z           at Test.bound [as _assert] (/home/runner/work/ethereumjs-monorepo/ethereumjs-monorepo/node_modules/tape/lib/test.js:80:32)
2021-04-27T07:50:38.1098684Z           at Test.fail (/home/runner/work/ethereumjs-monorepo/ethereumjs-monorepo/node_modules/tape/lib/test.js:322:10)
2021-04-27T07:50:38.1100594Z           at Test.bound [as fail] (/home/runner/work/ethereumjs-monorepo/ethereumjs-monorepo/node_modules/tape/lib/test.js:80:32)
2021-04-27T07:50:38.1102817Z           at handleError (/home/runner/work/ethereumjs-monorepo/ethereumjs-monorepo/packages/vm/tests/BlockchainTestsRunner.ts:90:9)
2021-04-27T07:50:38.1104712Z           at runBlockchainTest (/home/runner/work/ethereumjs-monorepo/ethereumjs-monorepo/packages/vm/tests/BlockchainTestsRunner.ts:155:13)
2021-04-27T07:50:38.1106128Z   ...
2021-04-27T07:50:38.1107014Z not ok 12190 correct last header block
2021-04-27T07:50:38.1107580Z   ---
2021-04-27T07:50:38.1107934Z     operator: equal
2021-04-27T07:50:38.1108571Z     expected: |-
2021-04-27T07:50:38.1109743Z       '401b8e01995bb6acfcdd1719e5a4454baadc04a81155793a3edadc61a6f5236c'
2021-04-27T07:50:38.1110798Z     actual: |-
2021-04-27T07:50:38.1113214Z       'be2aecb38c392925f91434d910cd8dfb0db91f4855bfc5bdb3b3ee504ae32b2f'
2021-04-27T07:50:38.1115371Z     at: runBlockchainTest (/home/runner/work/ethereumjs-monorepo/ethereumjs-monorepo/packages/vm/tests/BlockchainTestsRunner.ts:158:5)
2021-04-27T07:50:38.1116342Z     stack: |-
2021-04-27T07:50:38.1116916Z       Error: correct last header block
2021-04-27T07:50:38.1118191Z           at Test.assert [as _assert] (/home/runner/work/ethereumjs-monorepo/ethereumjs-monorepo/node_modules/tape/lib/test.js:228:54)
2021-04-27T07:50:38.1131267Z           at Test.bound [as _assert] (/home/runner/work/ethereumjs-monorepo/ethereumjs-monorepo/node_modules/tape/lib/test.js:80:32)
2021-04-27T07:50:38.1134161Z           at Test.equal (/home/runner/work/ethereumjs-monorepo/ethereumjs-monorepo/node_modules/tape/lib/test.js:389:10)
2021-04-27T07:50:38.1136212Z           at Test.bound (/home/runner/work/ethereumjs-monorepo/ethereumjs-monorepo/node_modules/tape/lib/test.js:80:32)
2021-04-27T07:50:38.1138360Z           at runBlockchainTest (/home/runner/work/ethereumjs-monorepo/ethereumjs-monorepo/packages/vm/tests/BlockchainTestsRunner.ts:158:5)
2021-04-27T07:50:38.1141437Z           at /home/runner/work/ethereumjs-monorepo/ethereumjs-monorepo/packages/vm/tests/tester.ts:172:19
2021-04-27T07:50:38.1143749Z           at fileCallback (/home/runner/work/ethereumjs-monorepo/ethereumjs-monorepo/packages/vm/tests/testLoader.ts:60:11)
2021-04-27T07:50:38.1145007Z   ...
```

`vm-blockchain (Istanbul)`:

Same two tests.

**Comment by jochem-brouwer** [comment]
These tests are fixed in #1196, if you change the target branch to that one we can merge immediately.

**Comment by holgerd77** [comment]
@jochem-brouwer thanks, I will merge #1196 first and then update here.

**Comment by holgerd77** [comment]
@jochem-brouwer ah, interesting that this is running into a conflict on the submodule now:

image

😄 

Will do a force-push.

**Comment by holgerd77** [comment]
Have rebased here on top of #1196

**Comment by holgerd77** [comment]
Tests pass, ready for review! 😄

**Review by ryanio — APPROVED** [review]
nice, lgtm!

the `vm-api` run is taking 10 mins now though, comparing to a prior PR it was 8 mins. i'd say that these are getting too long and we should aim to cut it down to 5 mins to match the rest of the ci checks and ensure quick PRs. nobody likes waiting around 10 mins for CI to complete if we can manage to make it more efficient :)

**Comment by holgerd77** [comment]
@ryanio yeah, likely beneficial to do another round of some basic optimization here.

**Pull request merged**
