### PR TITLE
Add package level `lint:fix` back

### PR DESCRIPTION
**Pull request by acolytec3**
By request, this re-introduces package level `lint` and `lint:fix` npm scripts.  These will not run under normal circumstances but can be used to do package level linting.

### CODE REVIEW

**Review by holgerd77 — DISMISSED** [review]
LGTM

**Comment by holgerd77** [comment]
Ah, lint Check actually failing.

Also: is it then also possible to have the non-fix command available on package level as well?

**Review by holgerd77 — APPROVED** [review]
LGTM

**Comment by jochem-brouwer** [comment]
Great, thanks! :pray: :smile:

**Pull request merged**
