### PR TITLE
Common: allow Common with custom genesis state (for a custom chain)

### LINKED ISSUE #553: How to initialize the VM for a custom network with a custom genesis block
I'm creating this issue to document how to do this, as it's a somewhat intricate process that we should simplify, or at least create an example for it.

```ts
import Common from "ethereumjs-common";
import { toBuffer, bufferToHex, privateToAddress } from "ethereumjs-util";
import BN from "bn.js";
import VM from "ethereumjs-vm";
import Account from "ethereumjs-account";
import Blockchain from "ethereumjs-blockchain";
import { promisify } from "util";
import { StateManager } from "ethereumjs-vm/dist/state";
const Trie = require("merkle-patricia-tree/secure.js");

const BLOCK_GAS_LIMIT = 8000000;

interface GenesisAccount {
  balance: string;
  privateKey: string;
}

function getCurrentTimestamp(): number {
  return Math.ceil(new Date().getTime() / 1000);
}

async function createCustomNetworkVM() {
  const genesisAccounts: GenesisAccount[] = [
    {
      balance: "1000000000000000000123",
      privateKey:
        "0xe331b6d69882b4cb4ea581d88e0b604039a3de5967688d3dcffdd2270c0fd109"
    }
  ];

  // To create a custom network, we need a Common object with our custom
  // parameters.
  //
  // Depeding on which EthereumJS library you are using, you may want to set all
  // the parameters, or just a few.
  //
  // We are going to use the blokchain module, which creates its genesis block
  // based on the Common's params.
  //
  // One of those params is the root of the initial state trie. That trie
  // contains the initial set of accounts.
  //
  // We would normally use a StateManager to create such a state, but it
  // requires a Common, and we are doing this to create a Common. The solution
  // is to go deeper and directly use a Trie.
  const stateTrie = new Trie();
  const putIntoStateTrie = promisify(stateTrie.put.bind(stateTrie));
  for (const acc of genesisAccounts) {
    const balance = new BN(acc.balance);

    // We skip accounts with 0 balance, there's no need to include them.
    if (balance.eqn(0)) {
      continue;
    }

    const account = new Account({ balance: balance });
    const pk = toBuffer(acc.privateKey);
    const address = privateToAddress(pk);

    await putIntoStateTrie(address, account.serialize());
  }


  // Mimic precompiles activation. Not sure if this is necessary
  for (let i = 1; i <= 8; i++) {
    await putIntoStateTrie(
      new BN(i).toArrayLike(Buffer, "be", 20),
      new Account().serialize()
    );
  }

  const common = Common.forCustomChain(
    "mainnet",
    {
      chainId: 1337,
      networkId: 1337,
      name: "buidler-network",
      genesis: {
        timestamp: "0x" + getCurrentTimestamp().toString(16), // Any timestamp would do
        hash: "0x", // We don't set a hash, but the TS type requires a string, so we pass an empty Buffer.
        gasLimit: BLOCK_GAS_LIMIT,
        difficulty: 1, // Any value should work.
        nonce: "0x42", // We don't validate POW, so any value is ok
        extraData: "0x1234", // Anything could go here
        stateRoot: bufferToHex(stateTrie.root)
      }
    },
    "petersburg"
  );

  // We want to use the state trie we already created, so we create a
  // StateManager with it, and pass it into the VM.
  const stateManager = new StateManager({
    common: common as any, // TS error because of a version mismatch
    trie: stateTrie
  });

  const blockchain = new Blockchain({ 
    // We disable validation to avoid having to deal with POW. This disables
    // further validations. See https://github.com/ethereumjs/ethereumjs-blockchain/issues/120
    validate: false, 
    common 
  });

  return new VM({
    common: common as any, // TS error because of a version mismatch
    activatePrecompiles: true,
    stateManager,
    blockchain
  });
}

```

### PR DESCRIPTION
**Pull request by holgerd77**
Fixes #553

Base work for #1132 or follow-up PR

PR description see below

### CODE REVIEW

**Comment by holgerd77** [comment]
Ok, some background on this:

I initially implemented (~3 years ago) the genesis state access functionality in Common [separately](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/common#genesis-states) from the main Common class with the main argument that the large genesis account state from `mainnet` shouldn't go into the main Common class for performance reasons.

I now did some more in-depth tests and also did some memory usage checks with this [roughSizeOfObject()](https://stackoverflow.com/questions/1248302/how-to-get-the-size-of-a-javascript-object) function from StackOverflow and it turned out that this was actually a naive assumption and the genesis state files are actually not read at all when - as being done in this PR - the `require` calls are encapsulated in the respective function call. So the `mainnet.json` file is ~300kb large, calling `roughSizeOfObject()` on a newly instantiated Common with the changes from this PR gives a very mild 4k (I actually did some more tests I don't all want describe here to be really really sure).

So the base assumption which lead to this separation is actually wrong and we can safely integrate into Common, which is generally a lot more natural way of accessing the genesis state.

When having a closer look and doing some tests on the VM integration in [StateManager.generateCanonicalGenesis()](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/vm/src/state/stateManager.ts#L556) I realized that this new version actually *improves* the status quo since in the old version the whole (mainnet) genesis account state array actually *was* created on every run of the VM along the import of this `genesisStateByName` function from `Common` together with this global array in [genesisStates/index.js](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/common/src/genesisStates/index.ts#L3) in Common adding all genesis states (I manually tested and confirmed this). So until now every VM initialization was actually unnecessarily creating the mainnet dict with ~ 50.000 entries. This is now not the case any more with this new implementation.

Since the old way of accessing genesis state was so artificial and was created on false assumptions I also deprecated the two old functions along the way, think this should be a no-brainer.

This whole integration then prepared the ground (this was actually the main motivation 😋) to now also allow for adding genesis states along custom chain initializations which solves one open issue we have (see above) and is also preparatory work for the client.

Generally open for review, eventually one small question: I now decided to just return an empty array if `Common.genesisState()` is called on a custom chain with no genesis state provided. I could imagine that this might be more convenient for some use cases but we could alternatively also throw. No strong opinion here.

**Comment by holgerd77** [comment]
(`test-client-cli (goerli, full)` failure can be ignored)

**Review by acolytec3 — APPROVED** [review]
LGTM!  I was able to fire up a script, import multiple custom chains (including one with no genesis state), switch between them, and access genesis state items.

**Comment by acolytec3** [comment]
Do y'all think we should add a `pattern 3` to the docs on the where someone is importing multiple custom chains with a mix of having and not having genesis states or is that too much of an edge case?  

You have to code it like `const customChains: [IChain, GenesisState][] = [[testnet, genesisStateOne], [testnet2, genesisStateTwo], [testnet3, {}]]` to get it to work

**Comment by holgerd77** [comment]
> Do y'all think we should add a `pattern 3` to the docs on the where someone is importing multiple custom chains with a mix of having and not having genesis states or is that too much of an edge case?
 
Too much of an edge case I would say

**Pull request merged**
