### PR TITLE
Added client rpc eth tests for unsupported block params

### PR DESCRIPTION
**Pull request by emersonmacro**
Partially addresses #1227 for `eth` calls. In particular, added tests for unsupported `block` params (i.e. block !== `latest`). Hopefully will help out with the code coverage report.

### CODE REVIEW

**Comment by ryanio** [comment]
Hey @emersonmacro thanks for your PR, looks great.

I was planning on adding support for more block params soon. Basically if a block is passed in, we need to copy the VM, set the stateRoot back to the stateRoot of the specified block in the StateManager, then run the query (e.g. getBalance would use getAccount.balance).

I was planning on working on this soon, possibly next week, but if you want to give it a shot before then, feel free.

Otherwise I think we can still merge this PR in because we will still not have support for `pending` (we are just starting on our TxPool implementation) so I can update these tests for `pending` instead of `!== 'latest'` in a future PR.

**Comment by emersonmacro** [comment]
Hi @ryanio thanks for the feedback, and sounds good. I'm still new to the codebase so I've been easing into it by working on some tests. I'd be in favor of merging this PR if that's ok, and I may take a stab at the change you described - it might take me a while lol, so you'll probably get to it before I get it working. But the steps you laid out are super helpful. Cheers!

**Review by ryanio — APPROVED** [review]
lgtm!

**Review by ryanio — APPROVED** [review]

**Comment by emersonmacro** [comment]
Hi @ryanio thanks for merging!

I started looking into the code change you described, for passing in an actual block number. If you have a minute, I'd be interested in your feedback on this: https://github.com/emersonmacro/ethereumjs-monorepo/commit/fea486a295f504b4779695e20cd42b40b8b1d128.

I'm guessing there's a better approach than what I have there, but I was wondering if I'm on the right track.

**Comment by ryanio** [comment]
@emersonmacro looks like a great start. i would probably start with a utility function that accepts the string block param and returns a block, that can be used in the other methods. first it can check if it's "earliest" (gets the genesis block) or "latest" (gets the latest block). if it "pending" then it can return the unsupported error. next if it is a hex block number it can return that. then as a final catch it can return an error that it didn't understand the input.

some great tests to add would be to verify that it can correctly get values at prior block numbers.

**Comment by emersonmacro** [comment]
@ryanio Makes sense, thanks. I started working on an approach based on your description, but this week is really busy, so no worries if you want to move forward on it. I will try to keep working on it though.

**Comment by ryanio** [comment]
@emersonmacro ok thanks for the update! my plate is filling up too so we can see who can get to it first 😄 do you want to open a branch with what you have so far so I can better follow along?

**Comment by emersonmacro** [comment]
@ryanio For sure - I pushed up an update to the draft branch on my fork. I don't think what I have right now is very good, and typescript is complaining about a couple things... Still a work in progress :). https://github.com/ethereumjs/ethereumjs-monorepo/compare/master...emersonmacro:draft-support-block-param

Also, did you mean opening a branch on the main ethereumjs repo? Happy to do so but I didn't think I'd have write access to open one, but I might be wrong on that. I'm still kind of new to working with forks.

**Comment by ryanio** [comment]
great, thanks, just a branch on your own fork is totally fine for now.

**Comment by ryanio** [comment]
looks good, I would add "pending" as a case and return the unsupported error directly. then if the string doesn't start with "0x" you can return an error that says something like input cannot be parsed as a 0x-prefixed hex number or should be "earliest"|"latest".

**Pull request merged**
