### PR TITLE
Point hardhat tests to the upgrade branch

### PR DESCRIPTION
**Pull request by acolytec3**
WIP

### CODE REVIEW

**Comment by holgerd77** [comment]
Ah, interesting. Cool! 🙂

**Comment by acolytec3** [comment]
It's only cool if I get it to work :grimacing: I'm stumped at the moment though I suspect it's currently related to our beta releases somehow messing up the versioning in verdaccio.

**Comment by holgerd77** [comment]
Is this more about "helping HH to update" (and so even eventually leading to PRs on the HH side)? Or rather for finding inconsistencies in our own implementation?

(also asking because first possibility is likely also the job for the HH people to some greater extend?)

**Comment by acolytec3** [comment]
The main goals were to see if the job even worked, which it wasn't and then to give me a tracking sense of where their work was in terms of integrating (and maybe reveal any bugs in our code if it surfaces)

**Comment by holgerd77** [comment]
Outdated, will close.

**Pull request closed without merging**
