### PR TITLE
Monorepo: Set default hardfork to London

### LINKED ISSUE #1657: Common: Set Default HF to London
Part of: #1024 
Target branch: `develop`

The [DEFAULT_HARDFORK](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/common/src/index.ts#L357) in Common is still set to `istanbul`, this should be updated to `london` for the next round of breaking releases.

This is a further reaching change than one might initially anticipate since this setting binds all libraries together with a default HF, so there might be the need to adopt several test cases and the like where no HF is set on Common instatiation.

Generally a monorepo-wide search (exluding `ethereum-tests`) for "istanbul" is recommended to spot all the places to change.

Some I can think of right now (respectively partly have also found by search):

- Common README
- the `defaultHardfork` in all Common chain files, like [goerli.json](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/common/src/chains/goerli.json) (I wonder if this should rather be removed though for all chain files pointing to the (former) default HF `istanbul` since this seems redundant to me and - from looking at the Common init code - this is overwritten with the default HF anyhow. Setting exists so that one *can* deviate from a certain default HF, e.g. if the HF doesn't exist on a certain chain)
- There are also (Common) chain files in other libraries - e.g. for test setups - there one should have a (somewhat) closer look and see what to do (also taking the stuff written above into account)
- Mostly everywhere in the code docs where a `Common` instance is passed as an option to a library the default HF is mentioned (this should stay this way for usability reasons, people want to know)
- For the test chain files in Common (like testnet.json) - not sure - maybe remove as well and see how it goes, same for VM
- ~Very special thing: this whole `DEFAULT_HARDFORK` from the Tx library can now actually be removed again. This was especially introduced for new tx types like EIP-1559 since there the default HF needed to deviate from the too old `istanbul` HF. Not necessary any more.~ Actually, second thought: please keep and manually set to `london`, then we still have the infrastructure in place for a potential additional tx type where we again need to apply this logic

### PR DESCRIPTION
**Pull request by emersonmacro**
Closes #1657

### CODE REVIEW

**Comment by emersonmacro** [comment]
I skipped over the client tests and forgot to come back to them. I'll take a look at them tomorrow.

**Comment by emersonmacro** [comment]
@holgerd77 No problem - I had a feeling that might be the case, but it was at least helpful to identify the relevant tests. I also wanted to do a pass through the CI to see if there were any tests I didn't find locally. I'll close this and keep working on it.

One question that came up: should I update this paragraph in the `tx` README? https://github.com/ethereumjs/ethereumjs-monorepo/blob/develop/packages/tx/README.md?plain=1#L60

**Comment by emersonmacro** [comment]
Closing this for now to continue working on refactoring tests

**Comment by holgerd77** [comment]
> One question that came up: should I update this paragraph in the tx README? https://github.com/ethereumjs/ethereumjs-monorepo/blob/develop/packages/tx/README.md?plain=1#L60

I would cautiously say that it's ok to delete this whole sentence along the `develop` work.

**Comment by holgerd77** [comment]
Do I get this correctly that there hasn't been a replacement PR for this being opened yet? Or did I just forget?

**Comment by emersonmacro** [comment]
> Do I get this correctly that there hasn't been a replacement PR for this being opened yet? Or did I just forget?

@holgerd77 That's correct - I don't have the tests refactored yet. I have a question on the test data we use, like this for example (https://github.com/ethereumjs/ethereumjs-monorepo/blob/develop/packages/block/test/testdata/testdata.json). In my branch, if I remove the `hardfork: Hardfork.Istanbul` part of this line (https://github.com/ethereumjs/ethereumjs-monorepo/pull/1678/files#diff-5e26767037750597317a815e2bc28ff13e85897dde318118ad5a392d9ba10ddaR160), the test fails with this error:
```
# should test block validation on pow chain
TypeError: Cannot read properties of undefined (reading 'header')
    at BlockHeader._getHeaderByHash (/ethereumjs-monorepo/packages/block/src/header.ts:996:56)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processImmediate (node:internal/timers:437:9)
    at async BlockHeader.validate (/ethereumjs-monorepo/packages/block/src/header.ts:661:26)
    at async Block.validate (/ethereumjs-monorepo/packages/block/src/block.ts:285:5)
    at async Test.<anonymous> (/ethereumjs-monorepo/packages/block/test/block.spec.ts:168:7)
```

Does that mean I should generate new test data with London-compatible blocks, and have the relevant tests use the new test data? Or is there something I can change in the test itself to make it compatible with the existing test data even though the current hardfork is London?

**Comment by holgerd77** [comment]
Hmm, the proper naming and structuring of our test data is generally a bit underdeveloped. For this round I would have a tendency to keep the tests pre-London then and just instantiate with a pre-London Common. Maybe rename the `testdata` files to `testdata_pre-london` or so along.

**Comment by holgerd77** [comment]
Examples are breaking on CI, I guess we now also want to keep these going (@cbrzn thanks again for the integration)? 🙂

Also this needs a rebase now, be aware that this might be a bit tricky with the big changes from the BigInt PR merged in.

**Comment by emersonmacro** [comment]
@holgerd77 Yep, I'll take a look at the Examples tests.

There's also one client test that started failing and I'm a little stumped - it's the parse util here https://github.com/ethereumjs/ethereumjs-monorepo/blob/develop/packages/client/test/util/parse.spec.ts#L68. After making London the default hardfork, that test is now getting a different value from the expected hardcoded hash https://github.com/ethereumjs/ethereumjs-monorepo/runs/5284240878?check_suite_focus=true#step:5:859. I'm not sure what's causing it - any ideas?

Also, I haven't done a rebase before. I did `git merge develop` on my branch yesterday (here https://github.com/ethereumjs/ethereumjs-monorepo/pull/1678/commits/33fe6280af335d2d59a6cc1e4d370e0f8497f9a5), but I'm guessing I need to revert that commit and rebase. Is it `git rebase -i develop`?

**Comment by ryanio** [comment]
> There's also one client test that started failing and I'm a little stumped - it's the parse util here https://github.com/ethereumjs/ethereumjs-monorepo/blob/develop/packages/client/test/util/parse.spec.ts#L68. After making London the default hardfork, that test is now getting a different value from the expected hardcoded hash https://github.com/ethereumjs/ethereumjs-monorepo/runs/5284240878?check_suite_focus=true#step:5:859. I'm not sure what's causing it - any ideas?

I think this was me, I fixed it in my merge-kiln branch, you can copy over the [util/parse.ts](https://github.com/ethereumjs/ethereumjs-monorepo/pull/1712/files#diff-972b7562b7b37e37b85f42447f901a9dcd65484f78d16e42144ff8cee2c11f88) changes for now or ignore it and wait 1-2 weeks until we get this branch merged into master.

**Comment by holgerd77** [comment]
> Also, I haven't done a rebase before. I did git merge develop on my branch yesterday (here https://github.com/ethereumjs/ethereumjs-monorepo/commit/33fe6280af335d2d59a6cc1e4d370e0f8497f9a5), but I'm guessing I need to revert that commit and rebase. Is it git rebase -i develop?

Yes, please revert. 🙂 

Generally, rebase is simply `git rebase develop`, the `-i` is for `interactive`, you'll get a console there where you can rename/reorder/delete/... commits. This should be not necessary here (you can try though to use this for deleting the merge commit). On the normal rebase you then get instructions what to do in case of conflicts (likely).

Please do a branch backup before you do anything - especially if this is your first rebase. 😋

**Pull request closed without merging**
