### PR TITLE
 Toubleshoot codecov failures to upload coverage data

### PR DESCRIPTION
**Pull request by scorbajio**
This PR looks into issues that codecov is having with uploading coverage info. Currently, only the tx package is reporting coverage in codecov.

This PR was originally at #3375 before it was accidentally closed by resetting and force pushing the head commit.

### CODE REVIEW

**Comment by scorbajio** [comment]
Currently, the logs show codecov-action errors related to token issues, such as [here](https://github.com/ethereumjs/ethereumjs-monorepo/actions/runs/8838046027/job/24268274150?pr=3373):
```
[2024-04-25T19:13:10.355Z] ['error'] There was an error running the uploader: Error uploading to https://codecov.io: Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
```
Also, a [new major version](https://github.com/codecov/codecov-action/releases/tag/v4.3.0) of `codecov-action` has been released that does not support tokenless uploads.
In order to experiment with fixing the current errors or potentially even just updating to version 4.3.0 of `codecov-actions`, a codecov token can be used by adding it to github actions secrets.

Some resources on adding the token:
https://github.com/codecov/codecov-action
https://docs.codecov.com/docs/adding-the-codecov-token#github-actions
https://app.codecov.io/gh/ethereumjs/ethereumjs-monorepo/settings
 (edited)

**Comment by holgerd77** [comment]
What is the status of this?

CodeCov is not running RN, is this correct? It would generally be good (somewhat urgent) to have code coverage working again.

**Comment by scorbajio** [comment]
> What is the status of this?
> 
> CodeCov is not running RN, is this correct? It would generally be good (somewhat urgent) to have code coverage working again.

Yes, that's correct, `codecov-action@v3` errors out currently as can be seen in the above [comment](https://github.com/ethereumjs/ethereumjs-monorepo/pull/3376#issuecomment-2088097535) and also, from a more recent CI run, [here](https://github.com/ethereumjs/ethereumjs-monorepo/actions/runs/11261681245/job/31315714837?pr=3734):
```
[2024-10-09T19:25:07.565Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 429 - {"message":"Rate limit reached. Please upload with the Codecov repository upload token to resolve issue. Expected time to availability: 2866s."}
```


In this PR, I've changed a workflow file to upload a token. This token needs to be added by the CodeCov and Github repo admin (can see [this](https://docs.codecov.com/docs/adding-the-codecov-token#github-actions) article for help with doing so). @holgerd77 would you or someone with access be able to add this token to the repo? This may be enough to unblock us for now, and I would be able to also look into upgrading `codecov-action@v3` to the newest major version.

**Comment by holgerd77** [comment]
@scorbajio ah ok, yes I do remember the token request, sorry for not follwing up! 😬

Have now added following the instructions you linked! Would be great if you can re-pick this up! Living without coverage for far too long already! 🙂

**Comment by scorbajio** [comment]
As can be seen [on codecov](https://app.codecov.io/github/ethereumjs/ethereumjs-monorepo/tree/troubleshoot-coverage-upload-failure/packages), uploads of coverage data is successfully happening as expected. The issue was the secrets were not being passed from the `build.yml` file job that was calling the mpt build job, so this `secrets: inherit` fixes the issue. codecov-actions has been upgraded to v4 with this change as well.

**Review by acolytec3 — APPROVED** [review]
Well done sir! LGTM

**Comment by holgerd77** [comment]
Cool! 🎉

**Pull request merged**
