### PR TITLE
Update: README.md -> Graph

### PR DESCRIPTION
**Pull request by xdrkush**
add lisibility on schema

```mermaid
 graph TD
   vm{vm}
   client{client}
   ethash --> blockchain
   ethash --> client
   devp2p --> client
   block --> client
   block --> blockchain
   block --> ethash
   block --> vm
   blockchain --> client
   blockchain --> vm
   trie --> client
   trie --> vm
   trie --> blockchain
   trie --> block
   trie --> statemanager
   common --> block
   common --> statemanager
   common --> tx
   common --> blockchain
   common --> vm
   common --> evm
   common --> client
   common --> devp2p
   evm --> vm
   evm --> client
   tx --> block
   tx --> vm
   vm --> client
   statemanager --> vm
```

### CODE REVIEW

**Comment by acolytec3** [comment]
Thank you for the contribution but this doesn't seem to be making any actual updates to the package network graph so closing for now.  If you feel this is in error, please reopen and give more details as to what improvement you are trying to make and we'll be happy to review again.

**Comment by holgerd77** [comment]
Ah, to be fair, this does improve diagram layouting though by reducing on various line crossings, so I guess we can really take this in, thanks for the contribution!

**Comment by xdrkush** [comment]
hi,
So yes exactly I did not touch the overall architecture, but I just added readability to the graph by preventing the crossing of lines as much as possible.

**Comment by holgerd77** [comment]
Rebased this via UI.

**Review by holgerd77 — APPROVED** [review]
LGTM, will admin-merge since no code parts touched.

**Comment by holgerd77** [comment]
Update: ah, I guess maybe I'll try to actually break with this habit a bit - at least if not necessary - since this always leads to an email-cascade hammering in notifying about cancelled jobs (guess for you guys too?).

So will just wait respectively merge later if possible/not hindering the process.

**Pull request merged**
