### PR TITLE
Remove trusted setups from build

### PR DESCRIPTION
**Pull request by acolytec3**
Moves the `trusted_setup` out of `src` so it's no longer included in the `tx` bundle by default.  Also updates the readme to provide guidance on how to set up the dev environment to work with blob transactions.

### CODE REVIEW

**Review by g11tech — APPROVED** [review]
lgtm

**Comment by holgerd77** [comment]
Rebased this via UI.

**Comment by holgerd77** [comment]
Rebased this and renamed `trusted_setup.txt` to `devnet4.txt` to reduce the risk that people use this at some point in production.

**Review by holgerd77 — APPROVED** [review]
LGTM

**Pull request merged**
