### PR TITLE
Update EOF to current spec

### PR DESCRIPTION
**Pull request by ScottyPoi**
Addressing issue #2398 

> Our current implementation of EIP-3540 EOF code validation in `evm/src/eof.ts` uses an older version of the reference implementation that is no longer present in the EIP.... 

1. `eofCodeAnalysis`  updated to match the [current reference implementation](https://eips.ethereum.org/EIPS/eip-3540#reference-implementation) for code validation

1. EOF checks updated in `evm.ts` and `interpreter.ts` and the `FORMAT` and `MAGIC` constants exported by `eof.ts` consolidated to just `MAGIC`

1. `loadEOFCode` in `evm/src/eof.ts`  revised to just pull the code section from the EOF container directly by reading the EOF header to get the code section and do subArray (or slice) to get the code section rather than using the `codeAnalysis`.

----

#### `/evm/eofContainer.ts`
- Class objects for EOF components
  - SectionHeader
    - sectionKind
    - sectionSize(s)
  - EOFHeader
    - typeSize
    - numCodeSections
    - codeSize
    - dataSize
  - TypeSection
    - inputs
    - outputs
    - maxStackHeight
  - EOFBody
    - typeSections
    - codeSections
    - dataSection
  - EOFContainer
    - eofHeader
    - eofBody
- validate()
- toBuffer()
- fromBuffer()
- *helper methods*
  - `header.sectionHeaders()`
  - `header.sectionSizes()`
  - `body.size()`
  - `body.sections()`
  - `body.sectionSizes()`

### CODE REVIEW

**Comment by jochem-brouwer** [comment]
Thanks @ScottyPoi, but I think we should do a complete overhaul now that the EIPs have been updated again... (I plan to do this in https://github.com/ethereumjs/ethereumjs-monorepo/pull/2453)

**Comment by ScottyPoi** [comment]
Cool -- I have gone a bit farther. I'll compare with what you've done.   Even if I didn't do anything new, it was useful to me 😋

**Comment by jochem-brouwer** [comment]
Could you push your changes? :smile:

**Comment by jochem-brouwer** [comment]
I have somewhat started doing this overhaul but a lot, if not all, needs to be rewritten I think (because the spec has changed almost everything)

**Comment by jochem-brouwer** [comment]
See this commit, this should bring eof validation up-to-date with latest spec https://github.com/ethereumjs/ethereumjs-monorepo/pull/2453/commits/8163a81d0f8aabdc7f633581902d20869e2e9bdc

(Note: this does not build, because I have un-exported some methods)

**Comment by ScottyPoi** [comment]
@jochem-brouwer - 

Let me know how you feel about the approach I took in `eofTypes.ts`.

**Comment by jochem-brouwer** [comment]
@ScottyPoi this is very well structured and looks very good. I have some remarks though:

The `buffer()` method seems to convert the contents of an EOF header (or section) back into a Buffer. This is nice, but does it have practical usage..? This would actually be the task of the compiler (e.g. solidity) to create these buffers. It is our task to only verify it (although this would be a very nice helper function I'd say to write tests).

I think your approach is the way to go, I now have a very ugly verifier: see https://github.com/ethereumjs/ethereumjs-monorepo/pull/2453/files and then `eof.ts`

However it seems like we are now somewhat doing the same work at almost the same time, could you ping me if you work on EOF on discord? :smile: And should we start targeting PR #2453 to move all big EOF stuff in there?

I will continue with my rather ugly verifier for now but we should update it to a more structured way (like how you wrote the eof container!)

**Comment by jochem-brouwer** [comment]
@ScottyPoi also see https://github.com/shemnon/besu/blob/b39ada871bbc95638b451a2f50e437a6028e5883/evm/src/main/java/org/hyperledger/besu/evm/code/EOFLayout.java

**Comment by jochem-brouwer** [comment]
I am going to merge this format into #2465 if that is ok :)

**Comment by jochem-brouwer** [comment]
I will close here, so we can continue on #2453?

**Pull request closed without merging**
