### PR TITLE
allforks: Remove 4844, ssz and kzg from maintenance-v6

### PR DESCRIPTION
**Pull request by g11tech**
since 4844, ssz, kzg is no more relevant to this maintenance branch v6, removing it for benefit of the users of this branch

### CODE REVIEW

**Comment by holgerd77** [comment]
Oh.

Didn't expect this to be soo extensive.

Very brave!

**Comment by g11tech** [comment]
> (actually the client code base does not necessarily need to work (we could also remove the CI run), since we'll likely (surely) won't do any more client releases on this branch)

ahh yes! seems like all resolved ! lol

**Comment by holgerd77** [comment]
Removed the e2e-hardhat tests from CI here

**Comment by g11tech** [comment]
> This is ready, right?

Yes @holgerd77 this is GTG 👍

**Review by holgerd77 — APPROVED** [review]
Looks fantastic, thanks a lot for taking this on!

I guess I‘ll tackle a release round on this rather sooner than later, early next week or so, seems important to me.

**Pull request merged**
