### PR TITLE
client: snap protocol fetchers

### PR DESCRIPTION
**Pull request by scorbajio**
Continues the snap protocol implementation work. Work left to do:
- [ ] Build fetchers for accounts, storage slots, and bytecode, and just dump it into a mock MPT
- [ ] Build MPT and successfully run move the chain forward on a normal eth sync
- [ ] Chart out behavior of non static peer and map next steps

### CODE REVIEW

**Comment by holgerd77** [comment]
You are somewhat off with where you branched off here (lot's of old commits in), can you resubmit in a clean state?

**Comment by scorbajio** [comment]
@holgerd77 Should I be continuously syncing with master on this branch?

**Comment by holgerd77** [comment]
> @holgerd77 Should I be continuously syncing with master on this branch?

I am not sure if I understand your question, so if you want to continue to work here, you have to bring this to the latest base branch state at some point (of course).

Can you maybe write a bit what's the state of this PR, what is left to do, when/if you would plan to continue.

**Comment by scorbajio** [comment]
> > @holgerd77 Should I be continuously syncing with master on this branch?
> 
> I am not sure if I understand your question, so if you want to continue to work here, you have to bring this to the latest base branch state at some point (of course).
> 
> Can you maybe write a bit what's the state of this PR, what is left to do, when/if you would plan to continue.
Thanks for clarifying, some of the changes from #1897 aren't in this PR (like the `forceSnapSync` option) but do show up in master. Not sure if I missed something while I was branching. Might need to just pull from `master` to include those changes.

Work that needs to be done:
- [ ] First, we need to capture data for `AccountRange`, `StorageRanges`, `ByteCodes`, and `TrieNodes` to get practical visibility into what the data for those calls include and how to use them
- [ ] Create account fetcher
- [ ] Create storage fetcher
- [ ] Create byte code fetcher
- [ ] Create trie node fetcher

My understanding is that there needs to be one fetcher per each `get` call defined in the snap specs. Open to suggestions on this design plan.

**Comment by scorbajio** [comment]
I see so `snap-client` has been merged and deleted and I need to reraise a new PR to merge with `master`.

**Comment by scorbajio** [comment]
Work is being continued at #2107 .

**Pull request closed without merging**
