### PR TITLE
Troubleshoot failing node versions tests: Adjust timeouts in devp2p tests to avoid race conditions

### PR DESCRIPTION
**Pull request by scorbajio**
While investigating #2865, after making a busy wait and timeout longer, the devp2p tests would pass more consistently than before when running them locally. This will give more consistent results for test runs.

### CODE REVIEW

**Comment by holgerd77** [comment]
Rebased this via UI

**Comment by gabrocheleau** [comment]
Any insight as to why tests would run slower on Node20 vs Node18?

**Comment by acolytec3** [comment]
Can you rename the PR to represent what it's actually doing?  Something like "Adjust timeouts in devp2p tests to avoid race conditions"

**Review by acolytec3 — APPROVED** [review]
LGTM

**Comment by scorbajio** [comment]
> Any insight as to why tests would run slower on Node20 vs Node18? Seems surprising.

It seems to be unrelated to versions, but rather related to the vitest refactors. Tests in devp2p and client packages have shown to time out intermittently. Relaxing timing constraints keeps tests from timing out, for now.

**Pull request merged**
