### PR TITLE
client: move TxPool to FullEthereumService

### PR DESCRIPTION
**Pull request by ryanio**
As a preparatory step for a post-merge client and integrating optimistic sync, this PR moves TxPool from FullSync to FullEthereumService to better operate independently of FullSync status.

We moved vm execution for similar reasons in #1663. I couldn't find a reason to keep execution in the `client` class, so I have moved it to the FullEthereumService as well, where it is mostly used.

### CODE REVIEW

**Comment by ryanio** [comment]
I think my only TODO, unrelated to this PR, would be to add some coverage for `executeBlocks`, I think that would be nice to have as it seemed like it didn't have any related tests when I moved it from the client class to execution class.

**Comment by g11tech** [comment]
Sync is looking good :rocket:  :heart:  w.r.t. execution movement, waiting for the clients to syncup to check txpool

**Review by g11tech — APPROVED** [review]
LGTM, tested by hooking up metamask and sending a transaction,
it got accepted by the txpool and got confirmed as well

image

**Comment by ryanio** [comment]
@g11tech amazing, thank you! will merge this in then. really happy and proud of the code cleanup. ok one last nit commit :)

**Comment by holgerd77** [comment]
Cool PR, yeah, this seems to make a lot of sense! 👍 💯 ❤️

Nice. 🙂

**Pull request merged**
