### PR TITLE
tx: remove default hardfork from tx classes

### PR DESCRIPTION
**Pull request by gabrocheleau**
Addresses the issue that was brought up in this comment: https://github.com/ethereumjs/ethereumjs-monorepo/pull/2767#discussion_r1226359471

### CODE REVIEW

**Comment by acolytec3** [comment]
Should we also remove the entire [`DEFAULT_HARDFORK`](https://github.com/ethereumjs/ethereumjs-monorepo/blob/0a6bf5e70cf0b7ee68bb67be76a7d528df6d1af7/packages/tx/src/baseTransaction.ts#L92) from the `BaseTransaction` class?  Shouldn't we just go straight to the default hardfork specified by `common` rather than continue to retain this default hardfork in `BaseTransaction`?

**Review by scorbajio — DISMISSED** [review]
ACK

**Comment by gabrocheleau** [comment]
> Should we also remove the entire [`DEFAULT_HARDFORK`](https://github.com/ethereumjs/ethereumjs-monorepo/blob/0a6bf5e70cf0b7ee68bb67be76a7d528df6d1af7/packages/tx/src/baseTransaction.ts#L92) from the `BaseTransaction` class? Shouldn't we just go straight to the default hardfork specified by `common` rather than continue to retain this default hardfork in `BaseTransaction`?

Oh, definitely, I just missed that BaseTransaction has a Default hardfork too

**Review by acolytec3 — APPROVED** [review]
LGTM

**Comment by holgerd77** [comment]
Nice, yes, this whole `DEFAULT_HARDFORK` thing was some overthinking when new tx types came in and we were still on an older HF and wanted people to just instantiate a new tx type "out of the box".

So basically the same situation as we have with 4844 blob tx right now, but I now feel it's very much ok and even more transparent and clear that in these cases there is the need to instantiate a Common.

**Pull request merged**
