### PR TITLE
statemanager: Support using hashed account and storage tries 

### LINKED ISSUE #2343: Support using hashed account and storage tries
Currently, in order to put an account into the state manager, it has to be done so using the `putAccount` function, which requires an account address. During snap sync, account addresses are not known, only their hash. In order to store state from snap sync in state manager, it is necessary to add this functionality.

Also see #2345.

### PR DESCRIPTION
**Pull request by scorbajio**
Fixes #2343.

### CODE REVIEW

**Comment by holgerd77** [comment]
What is the state of this?

**Comment by scorbajio** [comment]
> What is the state of this?

I just pushed a few commits I was working on. Working through some failing tests. I'm currently focusing on getting the fetchers working for SNAP sync, so I haven't had much time to dedicate to this PR. I will come back to this though after achieving full static snap sync.

**Comment by holgerd77** [comment]
Here a lot of tests are still failing. Is this review request nevertheless intended?

**Comment by scorbajio** [comment]
> Here a lot of tests are still failing. Is this review request nevertheless intended?

It was an accident. This PR is still being worked on.

**Comment by holgerd77** [comment]
Just a note: if this is picked up work should be done towards `develop-v7`. Let's generally please discuss the structure and integration before this is continued.

**Comment by scorbajio** [comment]
The issue this functionality was aiming to resolve has been resolved by #2950.

**Pull request closed without merging**
