### PR TITLE
 VM: runTx(), runBlock(), buildBlock() Standalone Methods

### PR DESCRIPTION
**Pull request by holgerd77**
Addresses #3522

First round on replacing the VM core class based methods with function calls by remove the bindings.

Feel free to pick up if wanted!

### CODE REVIEW

**Comment by jochem-brouwer** [comment]
I think this should be ready for review now.

Small side note, upon checking `vm.ts` to see whats left, we have a huge `emitEVMProfile` method there, which does NOT call into `this` anywhere, so we can also remove that!

**Comment by holgerd77** [comment]
Can you do in a separate PR please?

**Comment by jochem-brouwer** [comment]
Ok, went ahead and also moved `emitEVMProfile` to a separate file. 

This will only help if the end user only uses `buildBlock` (which is likely the least popular method of VM), but this was a simple optimization so I think this is OK.

**Review by holgerd77 — COMMENTED** [review]
Very cool! 👏 

(will admin-merge)

**Pull request merged**
