### PR TITLE
common: move description string from being an object field to a comment

### PR DESCRIPTION
**Pull request by scorbajio**
This change is inspired by #3448 and refactors the following files by removing any description string fields and instead including them as comments to reduce code size:
* `eips.ts`
* `hardforks.ts`

### CODE REVIEW

**Review by holgerd77 — COMMENTED** [review]
Ah, one step further please, so the `v` (+ the surrounding dict) should be killed completely! 🙂

**Comment by holgerd77** [comment]
Can you also please post a set of pre and post work numbers here so that we always have these comparison values in the PRs themselves? (Simply the two files sizes in KB pre/post should be enough in this case I guess)

**Comment by scorbajio** [comment]
It seems like some tests that directly access the `v` field are failing, will clean those up, but the refactor seems to be successful, with the following results for the following test code:
```
import { Chain, Common, Hardfork } from '@ethereumjs/common'

const c = new Common({ chain: Chain.Mainnet, hardfork: Hardfork.Prague })
console.log(c.chainId())
```
Before: out1.mjs  162.0kb
After: out1.mjs  187.4kb

I wasn't able to import the `EIPs` dictionary since it's not being exported in the index file, although since it's being accessed indirectly by other imports, results should still include the size reduction it's gone through (although not entirely sure on this, may need confirmation).

**Comment by scorbajio** [comment]
I wasn't able to locally recreate any of the failing vm-api or test-wallet tests, so I just triggered a rerun to double check the CI results.

**Review by holgerd77 — APPROVED** [review]
Nice, cool, that we have a fix here!

Will merge.

**Pull request merged**
