### PR TITLE
Fix engine-cancun hive tests

### PR DESCRIPTION
**Pull request by jochem-brouwer**
Closes https://github.com/ethereumjs/ethereumjs-monorepo/issues/3275

### CODE REVIEW

**Comment by holgerd77** [comment]
Is this still a fix to take in?

**Comment by jochem-brouwer** [comment]
If someone gets to fixing failing hive tests then this likely is a start to fixing (some) of those.

Can also spin up hive to see if it fixes some tests to directly merge (and close if it actually causes more trouble)

**Comment by holgerd77** [comment]
> Can also spin up hive to see if it fixes some tests to directly merge (and close if it actually causes more trouble)

Yes, these super old PRs actually cause more trouble than it's worth, so if this here is relevant and not does any harm it would be good if we can quickly merge here and then build other stuff on top.

**Comment by jochem-brouwer** [comment]
Ah right, I see, we now have merge conflicts which indeed take (some) time to resolve.

I will spin up hive ASAP and fix those conflicts and then will either close or mark it as ready-to-review asap :)

**Comment by holgerd77** [comment]
Ok, thanks, but just for my understanding: so this has *not* been tested in Hive yet? (you just "did it"?)

**Comment by jochem-brouwer** [comment]
This PR is rather old so I can't say 100% sure, but due to the reason that this is linked to an issue which lists failing hive tests I am rather sure that I have just started at the top from those failing hive tests and then started to fix them one-by-one (verifying that they now pass in hive). The reason that I kept this as "WIP" (and draft) is that I (likely) wanted to solve all those problems listed in the issue in this PR, rather than a few.

**Comment by holgerd77** [comment]
Ok, let's really please move away from this "solve all" philosophy and address one-by-one or topic-by-topic, this otherwise tends to get sticky! 🙂

**Comment by jochem-brouwer** [comment]
I will check this out ASAP and then either mark this as review or close it, will also keep the "don't do all" suggestion in mind for PRs resembling this one :smile: :+1:

**Comment by jochem-brouwer** [comment]
Command used: `./hive --sim ethereum/engine --client ethereumjs --client-file configs/cancun.yaml --docker.output --sim.limit engine-cancun`
Branch tests on master: `INFO[10-11|18:28:21] simulation ethereum/engine finished      suites=1 tests=227 failed=39`

(now running on this PR after I fix the conflicts)

**Comment by jochem-brouwer** [comment]
Wait, I should update tests (will do tomorrow)

**Comment by jochem-brouwer** [comment]
Tests should be fixed, ready for review!

**Review by acolytec3 — APPROVED** [review]
LGTM

**Pull request merged**
