### PR TITLE
util: check that hex to byte conversion is valid in hexToBytes

### PR DESCRIPTION
**Pull request by gabrocheleau**
This addresses an issue where an invalid hex (e.g. `'0x\x19Ethereum Signed Message:\n32')` ) wouldn't throw. 

We now validate that every parsing of hex to int (through parseInt in base 16) returns a valid int and not a NaN.

### CODE REVIEW

**Comment by jochem-brouwer** [comment]
Have tested, with and without checks:

```
jochem@jochem-OMEN-Laptop-15-ek1xxx:~/Documents/ejs2/hive/clients/ethereumjs/ethereumjs-monorepo/packages/util$ ts-node ./test/test
hexToBytes: 446.597ms
jochem@jochem-OMEN-Laptop-15-ek1xxx:~/Documents/ejs2/hive/clients/ethereumjs/ethereumjs-monorepo/packages/util$ ts-node ./test/test
hexToBytes: 449.86ms
jochem@jochem-OMEN-Laptop-15-ek1xxx:~/Documents/ejs2/hive/clients/ethereumjs/ethereumjs-monorepo/packages/util$ ts-node ./test/test
hexToBytes: 443.832ms
jochem@jochem-OMEN-Laptop-15-ek1xxx:~/Documents/ejs2/hive/clients/ethereumjs/ethereumjs-monorepo/packages/util$ npm run build

> @ethereumjs/util@9.0.1 build
> ../../config/cli/ts-build.sh

[Node build] Using tsconfig.prod.cjs.json
> tsc --build ./tsconfig.prod.cjs.json
[Node build] Working... DONE

[ESM build] Using tsconfig.prod.esm.json
> tsc --build ./tsconfig.prod.esm.json
[ESM build] Working... DONE

[Post Build Fixes]Adding ./dist/cjs/package.json
Adding ./dist/esm/package.json


jochem@jochem-OMEN-Laptop-15-ek1xxx:~/Documents/ejs2/hive/clients/ethereumjs/ethereumjs-monorepo/packages/util$ ts-node ./test/test
hexToBytes: 428.618ms
jochem@jochem-OMEN-Laptop-15-ek1xxx:~/Documents/ejs2/hive/clients/ethereumjs/ethereumjs-monorepo/packages/util$ ts-node ./test/test
hexToBytes: 442.045ms
jochem@jochem-OMEN-Laptop-15-ek1xxx:~/Documents/ejs2/hive/clients/ethereumjs/ethereumjs-monorepo/packages/util$ ts-node ./test/test
hexToBytes: 445.398ms
```

**Comment by jochem-brouwer** [comment]
Performance influence is thus neglegible, but before merging would like an opinion from @acolytec3 @holgerd77

**Review by acolytec3 — APPROVED** [review]
LGTM!

**Review by acolytec3 — APPROVED** [review]
LGTM

**Comment by holgerd77** [comment]
Did also a simple performance test here, for these kind of utility method test a simple one liner in ts-node or so also always work pretty well:

```typescript
console.time('t'); for (let i=0; i<100000; i++) { hexToBytes(`0x123456789${i}`) }; console.timeEnd('t');
```

Can confirm that there seems to be no significant differences in performance. 🙂

**Pull request merged**
