### PR TITLE
Add eth_getTransactionByBlockHashAndIndex RPC Endpoint

### PR DESCRIPTION
**Pull request by JowieXiang**
Adding `eth_getTransactionByBlockHashAndIndex` RPC endpoint.

### CODE REVIEW

**Comment by acolytec3** [comment]
This looks good so far. Will review again once the tests are added.

**Review by acolytec3 — APPROVED** [review]
LGTM!  Will merge once the tests pass.

**Comment by JowieXiang** [comment]
Seems one existing test is failing 
```
# should sync to next subchain head or chain height
ok 677 should sync block 5 and 4
ok 678 should target syncing all the way to chain
not ok 679 TypeError: Cannot read properties of null (reading 'first')
  ---
    operator: error
    stack: |-
      TypeError: Cannot read properties of null (reading 'first')
          at Test.<anonymous> (/home/runner/work/ethereumjs-monorepo/ethereumjs-monorepo/packages/client/test/sync/beaconsync.spec.ts:146:27)
  ...
```

**Comment by acolytec3** [comment]
There's a race condition somewhere in one of the client sync tests where this occasionally fails and we just haven't chased it down yet.  I'm rerunning it now and will merge once it passes.

**Comment by JowieXiang** [comment]
> There's a race condition somewhere in one of the client sync tests where this occasionally fails and we just haven't chased it down yet. I'm rerunning it now and will merge once it passes.

I can look into that if it does not require too much insider knowledge and is not very pressing. Or I can proceed with the other JSON-RPC API. Thx :)

**Comment by acolytec3** [comment]
> > There's a race condition somewhere in one of the client sync tests where this occasionally fails and we just haven't chased it down yet. I'm rerunning it now and will merge once it passes.
> 
> I can look into that if it does not require too much insider knowledge and is not very pressing. Or I can proceed with the other JSON-RPC API. Thx :)

I honestly don't even know how to reproduce it so probably not a simple thing to chase down unfortunately.  Maybe the other RPC endpoint would be a good next step.

**Comment by JowieXiang** [comment]
> > > There's a race condition somewhere in one of the client sync tests where this occasionally fails and we just haven't chased it down yet. I'm rerunning it now and will merge once it passes.
> > 
> > 
> > I can look into that if it does not require too much insider knowledge and is not very pressing. Or I can proceed with the other JSON-RPC API. Thx :)
> 
> I honestly don't even know how to reproduce it so probably not a simple thing to chase down unfortunately. Maybe the other RPC endpoint would be a good next step.

Understood. Thx~

**Pull request merged**
