### PR TITLE
statemanager: Fix statemanager Browser Example

### PR DESCRIPTION
**Pull request by scorbajio**
The `statemanager` package browser example has two errors when it's run. The first error comes from referencing `process` in the trie package:
```
trie.ts:105 Uncaught (in promise) ReferenceError: process is not defined
    at new Trie (trie.ts:105:18)
    at new DefaultStateManager (stateManager.ts:200:23)
    at run (browser.html:19:34)
    at browser.html:31:9
```
The second error results from using `hexStringToBytes` instead of `hexToBytes`. This change fixes both of these issues so that the example successfully runs in the browser.

### CODE REVIEW

**Comment by scorbajio** [comment]
The `process.env` issue is noted in #3140 as well.

**Review by holgerd77 — CHANGES_REQUESTED** [review]
We should really see that we fix this at the source level and make it easier for people to use the libraries in a browser context rather then adding new polyfills here or something (in fact we should also rather try to remove the other two vite plugins). Especially if it is about something as unimportant (for the end user) as our `DEBUG` functionality.

I just re-read the issue and discussion: so the `process` thing is really a non-issue and should be easy to fix at the source.

So @acolytec3 mentioned that we might want to disable this for browser (set it to `false` somewhere). This is actually already the case in the very most libraries (except for trie, guess it just got forgotten or something).

So this is the code:

```typescript
this.DEBUG =
      typeof window === 'undefined' ? process?.env?.DEBUG?.includes('ethjs') ?? false : false
```

So this translates to: if `window` object is not there (aka: not in browser), try use debugging. Otherwise don't.

We should just make sure that this snippet is consistently used within all libraries and then modfiy it on all occasions to not break in the browser.

One is actually already questioning why this is not working. 🤔 Likely something to do with the chaining of `?` operators or something.

So, when looking at the ESM build (by simply going into the `dist/esm` folder of `statemanager`), one can see that this translates to:

```typescript
this.DEBUG =
            typeof window === 'undefined' ? process?.env?.DEBUG?.includes('ethjs') ?? false : false;
```

This can easily tested in the browser by just going into a browser debug console - e.g. 
in Firefox by going to "Extras -> Browser Tools (or similar) -> Tools for Web Developers" (also some guide for @jochem-brouwer who mentioned he has not so much browser experience, really encourage you to give this a very short try, *absolutely* no rocket science!). 😄

grafik

As the screenshot shows the first version (coming from `statemanager`) evaluates properly. The second version (from `trie`) breaks.

So we should simply look through the libraries and just take the common pattern (from e.g. `statemanager`) and the problem should. be already solved.

**Comment by holgerd77** [comment]
Updated this via UI

**Review by holgerd77 — APPROVED** [review]
LGTM

**Pull request merged**
