### PR TITLE
Bump `@chainsafe/ssz` to `0.11.0`

### PR DESCRIPTION
**Pull request by FrederikBolding**
Bumps `@chainsafe/ssz` to `0.11.0`. 

The current version of `@chainsafe/ssz` uses an AssemblyScript based SHA-256 implementation that causes issues on some platforms since it requires `WebAssembly` for execution (e.g. in sites or extensions with strict CSPs). 

This new version uses a pure JS implementation (`@noble/hashes`) as the default hasher for SHA-256 and should fix some of these aforementioned incompatibility issues.

For more context see: https://github.com/ChainSafe/ssz/issues/313

### CODE REVIEW

**Comment by FrederikBolding** [comment]
Hmm, looks like the `exports` field in package.json is not supported by `karma` 🤔

**Comment by acolytec3** [comment]
I think I've resolved the karma import issue.  Will approve if CI passes

**Comment by FrederikBolding** [comment]
There could be an argument that this should be solved in the SSZ package itself. Since other tools may struggle with the exports configuration too.

**Review by holgerd77 — APPROVED** [review]
Thanks a lot, cool 🙂, will approve and merge!

**Comment by holgerd77** [comment]
> There could be an argument that this should be solved in the SSZ package itself. Since other tools may struggle with the exports configuration too.

If you solve this in the SSZ package let us know, then we likely also want to do another update on this. We have releases planned for roughly in 10 days or so, if this will happen it would be great if we could already take the updated version in.

**Pull request merged**
