### PR TITLE
VM v5.3.0 (Access List Gen & Block Builder) / Util v7.0.10 / Tx v3.1.2 Releases

### PR DESCRIPTION
**Pull request by holgerd77**

### CODE REVIEW

**Comment by holgerd77** [comment]
Blocked due to https://github.com/ethereumjs/ethereumjs-monorepo/pull/1170#issuecomment-810268855

**Comment by alcuadrado** [comment]
Is this coming in this release? https://github.com/ethereumjs/ethereumjs-monorepo/pull/1158 - It would be super helpful for us to be able to use it next week, as we are going to be implementing Berlin.

**Comment by holgerd77** [comment]
Ok, ready for review! 😄 

This needs a final approval from @alcuadrado, see discussion here https://github.com/ethereumjs/ethereumjs-monorepo/pull/1183#issuecomment-811484571 (//cc @jochem-brouwer).

**Comment by holgerd77** [comment]
This has now gotten it's ok from @alcuadrado in the chat. Ready for review. 😀

**Review by ryanio — APPROVED** [review]
looks good!

**Comment by holgerd77** [comment]
Just published the following releases on npm:

- `ethereumjs-util` [v7.0.10](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/ethereumjs-util%407.0.10)
- `@ethereumjs/tx` [v3.1.2](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Ftx%403.1.2)
- `@ethereumjs/vm` [v5.3.0](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fvm%405.3.0)

**Pull request merged**
