### PR TITLE
Add holesky dns url to supported chains info

### PR DESCRIPTION
**Pull request by scorbajio**
Also see [Holesky DNS Network for Peer Discovery](https://github.com/eth-clients/holesky/issues/58)

### CODE REVIEW

**Comment by holgerd77** [comment]
Rebased this via UI

**Comment by holgerd77** [comment]
Did you try and test here (e.g. via activating debug logs for devp2p) if DNS connection is going on successfully?

**Comment by scorbajio** [comment]
> Did you try and test here (e.g. via activating debug logs for devp2p) if DNS connection is going on successfully?

Seems to be working as expected:
```
[10-08|11:31:49] INFO Initializing Ethereumjs client version=v0.8.1 network=holesky chainId=17000 

...

2023-10-08T18:31:50.174Z devp2p:dns:dns got new peer candidate from DNS address=23.124.84.197
2023-10-08T18:31:50.313Z devp2p:dns:dns got new peer candidate from DNS address=194.33.40.147
2023-10-08T18:31:50.430Z devp2p:dns:dns got new peer candidate from DNS address=194.33.40.82
2023-10-08T18:31:50.504Z devp2p:dns:dns got new peer candidate from DNS address=159.203.110.190
2023-10-08T18:31:50.594Z devp2p:dns:dns got new peer candidate from DNS address=194.33.40.151

...

[10-08|11:31:55] WARN Engine RPC endpoint not activated on a post-Merge HF setup.
[10-08|11:31:55] INFO ---------------------------
[10-08|11:31:55] INFO Client started successfully
[10-08|11:31:55] INFO ---------------------------
```

**Review by acolytec3 — APPROVED** [review]
Shippit.

**Review by g11tech — APPROVED** [review]

**Comment by holgerd77** [comment]
@scorbajio cool, thanks for testing! 🤗

**Pull request merged**
