### PR TITLE
Fixes the RLP CLI

### PR DESCRIPTION
**Pull request by acolytec3**
Fixes the `rlp` CLI as reported in #3006.  Also adds a couple of simple CLI tests to verify that it works.

### CODE REVIEW

**Comment by holgerd77** [comment]
Great improvement 🤩, browser tests still failing though. Guess we simply do not want to run CLI tests in the browser, right?

**Comment by acolytec3** [comment]
> Great improvement 🤩, browser tests still failing though. Guess we simply do not want to run CLI tests in the browser, right?

🤦 I didn't even think about that. But yes, this test definitely won't run in the browser.

**Comment by acolytec3** [comment]
I'll have to add a vitest config there and have it skip that test for `npm run test:browser`

**Review by scorbajio — APPROVED** [review]
utACK

**Pull request merged**
