### PR TITLE
Codecov tuning

### PR DESCRIPTION
**Pull request by scorbajio**
The goal of this PR is to look into and fix the issues mentioned in #3134.

### CODE REVIEW

**Comment by holgerd77** [comment]
That's nice, that this gets tackled a bit again, would be really good if we get coverage a bit more integrated in our "everyday thinking" again! 😁

Everytime you get something working what was not working before, would be nice if you drop a short note here, I would be really interested to follow up on where and why this was actually hanging so much.

**Comment by scorbajio** [comment]
Now that their workflow and `package.json` files have been updated, the `wallet` and `genesis` packages are reporting coverage as expected. Both the `rlp` and `genesis` package coverage uploads fail codecov-side with only a `unusable report` error message. [This](https://docs.codecov.com/docs/error-reference) doc page gives four different possible reasons that could be causing the error, however, none of these reasons seem to be the causing the issue.

**Comment by holgerd77** [comment]
Updated this via UI

**Review by holgerd77 — APPROVED** [review]
Nice, LGTM!

**Comment by scorbajio** [comment]
I've created a ticket on the codecov-api repo about the `unusable report` error being too generic: https://github.com/codecov/codecov-api/issues/319.

**Comment by holgerd77** [comment]
> I've created a ticket on the codecov-api repo about the `unusable report` error being too generic: [codecov/codecov-api#319](https://github.com/codecov/codecov-api/issues/319).

Cool, not sure if anyone cares there, but let’s be brave! 🙂😅🤩

**Pull request merged**
