### PR TITLE
Use version 2.1.1 for ethereum-cryptography

### PR DESCRIPTION
**Pull request by scorbajio**

### CODE REVIEW

**Comment by holgerd77** [comment]
Hi there, not sure if you misread, but 2.1 is actually the broken version. We need to wait for a hot fix release here.

**Comment by scorbajio** [comment]
> 

I indeed misread.

**Comment by holgerd77** [comment]
2.1.1 is released, this can (and should, since we need for releases) now be updated quickly.

**Review by jochem-brouwer — APPROVED** [review]
Lgtm!

**Comment by holgerd77** [comment]
Please let's not start pinning dependencies now. This just does happen occasionally. But actually it is not happening that often and on the other hand it can happen on any of the other 50 or so dependencies we have and generally we have good reasons not to pin.

E.g. for this library there is already a 2.1.2 release out (we should update 😂)

**Pull request merged**
