### PR TITLE
Clean up logging in vm/evm

### PR DESCRIPTION
**Pull request by acolytec3**
Removes some cosmetic `0x` duplication that was leftover when `bytesToHex` was changed to produce prefixed hex strings.

Before fix --
`vm:tx Running tx=0x6143c89384b58f92fceda500e24e3ffe89a30c5441620fd1f3234a98ebc8a8d4 with caller=0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b gasLimit=3972796 to=0x095e7baea6a6c7c4c2dfeb977efac326af552d87 value=100000 data=`**0x0x00**` +0ms`

After fix --
`vm:tx Running tx=0x6143c89384b58f92fceda500e24e3ffe89a30c5441620fd1f3234a98ebc8a8d4 with caller=0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b gasLimit=3972796 to=0x095e7baea6a6c7c4c2dfeb977efac326af552d87 value=100000 data=`**0x00**` +0ms`

### CODE REVIEW

**Comment by holgerd77** [comment]
Rebased this via UI

**Comment by holgerd77** [comment]
Hmm, failing tests on walket and client. Maybe I’m generally not up to date yet on the state of master atm.

**Comment by acolytec3** [comment]
> Hmm, failing tests on walket and client. Maybe I’m generally not up to date yet on the state of master atm.

Yes, we've been having regular timeouts with that miner test recently. Thinking to disable it as well since it's a PoW test for the London hardfork

**Review by holgerd77 — APPROVED** [review]
LGTM

**Pull request merged**
