### PR TITLE
chore: rename `rlp` package to `@ethereumjs/rlp`

### PR DESCRIPTION
**Pull request by faustbrian**
- Resolves https://github.com/ethereumjs/ethereumjs-monorepo/issues/2058
- Should merge https://github.com/ethereumjs/ethereumjs-monorepo/pull/2093 first so that the sorting can be applied here too since the name changed so the package will move up in sorting

### CODE REVIEW

**Comment by holgerd77** [comment]
Hi there, just merged #2093, hope this didn't interfere too much with your imminent work here.

**Comment by holgerd77** [comment]
Ok, let me know when this is ready for review and merge.

**Review by acolytec3 — APPROVED** [review]
LGTM

**Review by acolytec3 — APPROVED** [review]

**Review by holgerd77 — APPROVED** [review]
Yes, LGTM, thanks a lot!

Will merge.

**Comment by holgerd77** [comment]
This is missing some doc updates in the [README](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/rlp) (I first-round-spotted the title and the install command), should be side added on some other PR or so.

**Pull request merged**
