### PR TITLE
devp2p: update example to berlin hard fork

### LINKED ISSUE #1003: devp2p: update check block in example to latest fork
The check block in the [peer-communication.ts](https://github.com/ethereumjs/ethereumjs-devp2p/blob/master/examples/peer-communication.ts) example should be updated to the latest fork.

The following PR can be used for guidance https://github.com/ethereumjs/ethereumjs-devp2p/pull/54 (this is missing the header RLP though).

### PR DESCRIPTION
**Pull request by acolytec3**
Fixes #1003.

I ran the script and verified that it does indeed run without any additional updates.

### CODE REVIEW

**Review by ryanio — APPROVED** [review]
looks good, this worked for me!

**Comment by ryanio** [comment]
as a next task, if you would like, were you able to give`peer-communication-les.ts` a try?

On a first run I am getting:

`Remove peer: 51.68.180.226:30303 - we disconnect, reason: SUBPROTOCOL_ERROR (16) (total: 0)`

although this might be a local issue for me, been having some odd issues with les and these subprotocol_errors, i checked with holger before and it didn't seem to be happening for him.

**Comment by acolytec3** [comment]
Sure, I'll take a peek

**Comment by acolytec3** [comment]
I'm seeing that happen as well, though it's not evident to me what the
source of the issue is yet.  Will do some further research.

**Comment by holgerd77** [comment]
Just some note of warning here: I guess this `peer-communication-les.ts` file hasn't been run for a *very* long time, at least I can state for myself that I guess that I've actually *never* run this file yet, lol. 😜 (since I have until now always more or less completely ignored the `LES` protocol). @ryanio did you ever got this to work respectively have run this in the last weeks to months?

Since otherwise this might be a relatively hard task to do, just for some context so that it's not getting too frustrating respectively being prepared. If this is going too deep into the protocol it might make sense to put aside again for now.

**Comment by acolytec3** [comment]
Okay, I'll spend another hour on it and then move on if I can't figure it
out.

**Pull request merged**
