### PR TITLE
client: fixes regarding beacon sync, vmexecution and further log improvs

### PR DESCRIPTION
**Pull request by g11tech**
if the backfill was left midway, on restart of client the sync wasn't starting since the sync `start` wasn't actually getting triggered

after this PR: sync gets triggered as soon as peers get connected

### CODE REVIEW

**Review by acolytec3 — DISMISSED** [review]

**Review by acolytec3 — COMMENTED** [review]
LGTM to me!

**Review by acolytec3 — APPROVED** [review]
LGTM (assuming CI passes and code coverage bumped sufficiently)

**Comment by g11tech** [comment]
> LGTM (assuming CI passes and code coverage bumped sufficiently)

@holgerd77  updates for log messages are incoming, pls let it stay unmerged for @holgerd77  :)

**Comment by holgerd77** [comment]
Client tests were not completely passing on the run before. 🤔 So this might need some additional attention.

Also would be good if @g11tech can have a look at the additional UI changes.

**Comment by holgerd77** [comment]
(best to review by just downloading the branch and run the client and see "how the changes feel" 🙂)

**Review by acolytec3 — APPROVED** [review]
LGTM

**Comment by holgerd77** [comment]
Thanks a lot for bringing this over the finish line! 😊🙏

**Pull request merged**
