### PR TITLE
Blockchain file reorganization

### PR DESCRIPTION
**Pull request by acolytec3**

### CODE REVIEW

**Comment by acolytec3** [comment]
@holgerd77 How does this version look?  Sorry, this whole land of renaming files while preserving history is brand new to me.  I used Gitlens on VS Code locally and it looks like it's now retaining the history of the renamed `blockchain.ts` file now

**Comment by holgerd77** [comment]
Thanks, that looks good, I guess GitHub won't show this any better. 🙂

Are you also adding a `types.ts` file and moving types, options,... in? That would be great!

Do we have anything else?

**Comment by holgerd77** [comment]
> I moved the types from `blockchain.ts` into their own file in the package/src directory. Is there any reason to bring the consensus or genesisState types into the master `types.ts` file? It feels pretty well compartmentalized to me.

Yeah, maybe we just leave there. Thanks, looks all good! 🙂

**Review by holgerd77 — APPROVED** [review]
LGTM

**Comment by jochem-brouwer** [comment]
It looks like git history of the files is lost here, did you use `git mv` here?

**Comment by acolytec3** [comment]
I [tried](https://github.com/ethereumjs/ethereumjs-monorepo/pull/1978), and [tried](https://github.com/ethereumjs/ethereumjs-monorepo/pull/1980), and [tried](https://github.com/ethereumjs/ethereumjs-monorepo/pull/1981), and [tried](https://github.com/ethereumjs/ethereumjs-monorepo/pull/1986). :sweat_smile:

**Comment by holgerd77** [comment]
> I [tried](https://github.com/ethereumjs/ethereumjs-monorepo/pull/1978), and [tried](https://github.com/ethereumjs/ethereumjs-monorepo/pull/1980), and [tried](https://github.com/ethereumjs/ethereumjs-monorepo/pull/1981), and [tried](https://github.com/ethereumjs/ethereumjs-monorepo/pull/1986). 😅

🙂 😂

Yes, impressively hard stuff. Strange sometimes.

**Pull request merged**
