### PR TITLE
util: upgrade deps

### PR DESCRIPTION
**Pull request by talentlessguy**
this PR upgrades ethereumjs-util dependencies which add a few fixes:

## bn.js `5.1.2 => 5.2.0`:

- fix: Buffer not using global in browser (#260)
- Add support for defined but not implemented Symbol.for (#252)

## rlp `2.2.4 => 2.2.6`

- Add bigint support
-  Fix long string decode

### CODE REVIEW

**Comment by ryanio** [comment]
hey @talentlessguy, these should already be included as we periodically refresh the lock file and they're specified with carats.

also for deps like `bn.js` that span across the whole monorepo we want to ensure we use the same version and not fragment - so if we upgrade a version of a dep we want to do it in all package.jsons that contain the same dependency (sorry I know that's tedious, but again since it's covered by the carat up to the next major version I don't think this PR is necessary).

**Comment by talentlessguy** [comment]
ok, closing then

**Comment by talentlessguy** [comment]
and please check my pr to rlp :)

**Comment by ryanio** [comment]
will do! thanks for sticking through on that one

**Pull request closed without merging**
