### PR TITLE
Bump EVM coverage

### PR DESCRIPTION
**Pull request by jochem-brouwer**
Let's see if this works.

### CODE REVIEW

**Comment by jochem-brouwer** [comment]
OK, no idea why this does not increase coverage.

**Comment by holgerd77** [comment]
Maybe we need to reference the EVM on the local file level in the VM test runner so that it is not referenced/seen as a package? 🤔

Can you try creating an explicit EVM in `GeneralStateTestRunner.ts` and pass this to the VM and import via the local path (Interpreter as well), so `import { EVM, Interpreter } from '../../evm/src/'` (something like this, not sure if path is correct)?

**Comment by jochem-brouwer** [comment]
Thanks a lot @holgerd77, this change made a lot of sense! EVM coverage now up +16.10%. I'd say this is ready for review.

**Comment by holgerd77** [comment]
Rebased this via UI.

**Review by holgerd77 — APPROVED** [review]
Ok, cool, great that this worked! 👍🙂

Then let's merge.

**Pull request merged**
