### PR TITLE
Add wit protocol

### PR DESCRIPTION
**Pull request by ryanio**
WIP. This PR adds [`wit/0`](https://github.com/ethereum/devp2p/blob/master/caps/wit.md) to devp2p and client.

### CODE REVIEW

**Comment by ryanio** [comment]
To get the trie hash nodes for a witness, I am thinking of adding a new option `reportTrieHashNodes` to `trie.get` that if true will collect and return the list of trie hash nodes accessed during the `get` call.

I haven't decided yet if it should return the info along the trie results (so if the boolean is true the return type contains the trieHashNodes data) or use the pattern in the VM to use an EventEmitter to emit the additional information, which I like but currently the trie doesn't have any EventEmitter usage so it would have to be newly added, but could then emit e.g. `trie.emit('trieHashNodes', queryKey, trieHashNodes)`

**Comment by holgerd77** [comment]
@ryanio I am sceptical if an EventEmitter is a fitting choice here. If you are doing this you are detaching the the processing code on the caller side from the `get()` call, so there will be some structure like:

```typescript

trie.on('trieHashNodes', () => { // process trie node hashes, here it might be somewhat more difficult to grasp on the context }

// Build up some context, where are these hashes used for
trie.get(key, true) // would it be oversized to use an options dict here?
```

You loose on the context here or you have to manually rebuild, so I guess from that PoV it would be easier to have:

```typescript

const hashes = trie.get(key, true)
// here we have the context directly (why where these hashes requested) and can directly do something with them
```

Not sure, also don't want to directly push too much in this direction, but let's have some exchange on this first on the up and downsides.

So what are the concrete upsides? Is this easier to implement to not have this tracked or something?

**Comment by ryanio** [comment]
that's a great point thanks for the feedback. i'll write some of this code today and we can evaluate it further based on how it looks.

i'm still digesting how to collect *all* the witnesses. the [wit spec](https://github.com/ethereum/devp2p/blob/master/caps/wit.md) says:

> Using the wit protocol, peers ask each other for the list of trie node hashes read during the execution of a particular block. This includes the following data:
>
> * Storage nodes
> * Bytecodes
> * Account nodes
> * Read during EVM execution
> * Read during transaction validation
> * Read during block reward calculation
> * Nodes read when generating the final state root (i.e. sometimes deleting data requires a trie refactor that reads nearby trie nodes)
> 
> The trie node hashes which are generated at the end of the block from existing data are not included. For example, the final state root hash is not included.

I asked @s1na and he said:
> Aha I was once working on sth similar and got the list of node hashes by monkey-patching trie._db.get as in [here](https://github.com/ethereumjs/ethereumjs-monorepo/pull/556/files#diff-67fff7fbd19b21c3a782aad2c3f9568e0c239fd5a7d05e523e9d971a54e69948R53)

**Comment by holgerd77** [comment]
This looks great already. 😄

**Comment by ryanio** [comment]
this is rather outdated now with the underlying codebase having changed. it can be used in the future to extract some of the wit logic, but not too much was connected and working, will close for now.

**Pull request closed without merging**
