### PR TITLE
Develop Branch Rebase Test - 2022-03-05 (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by holgerd77**
This is a test for the rebase of the `develop` branch to pass the CI tests.

Do not merge.

### CODE REVIEW

**Comment by holgerd77** [comment]
Client tests are still failing, with `not ok 601 parsed params correctly` in `client/test/util/parse.spec.ts` with a non-matching genesis hash.

Guess this has something to do with the work from #1741, @ryanio, can you see what is going on here?

**Comment by ryanio** [comment]
@holgerd77 with london being new common default, when creating the genesis header I had to explicitly call setHardforkByBlockNumber(0) to get back on chainstart, otherwise it was using baseFeePerGas and changing the hash. have opened a fix in #1765

**Comment by holgerd77** [comment]
> @holgerd77 with london being new common default, when creating the genesis header I had to explicitly call setHardforkByBlockNumber(0) to get back on chainstart, otherwise it was using baseFeePerGas and changing the hash. have opened a fix in #1765

Ah, could you push this fix directly towards this branch? That would be more convenient, otherwise I would go through the whole rebase process again. 🙄

**Comment by ryanio** [comment]
yes of course, sorry, didn't know what the next step would be, so I will merge my PR into his branch then

**Comment by holgerd77** [comment]
> yes of course, sorry, didn't know what the next step would be, so I will merge my PR into this branch then

Thanks 🙂, yes, optimally I guess there should always be an as small-as-possible timeframe between these develop-rebase-test PRs and the real push, otherwise things change too much in between.

But we'll see, this still needs to settle a bit.

**Comment by holgerd77** [comment]
Updated `develop` with the latest changes from here, will close.

**Pull request closed without merging**
