### PR TITLE
monorepo: add genesis to readme

### PR DESCRIPTION
**Pull request by gabrocheleau**
Adds the genesis package to the readme

### CODE REVIEW

**Comment by gabrocheleau** [comment]
Just noticed that I need to fix one of the links, on my phone now but will do when back home.

**Review by scorbajio — CHANGES_REQUESTED** [review]
I added a genesis workflow in #3098 so that link can be added to the README for the `tests` column. Other than that, this looks great!

**Review by acolytec3 — APPROVED** [review]
LGTM!

Small request for next time you do multiple doc updates, can you combine them into one so we don't have to rerun CI multiple times?

**Review by acolytec3 — APPROVED** [review]
I cherrypicked the new CI job from #3098 to this branch and updated the readme.  Should be ready to merge

**Pull request merged**
