### PR TITLE
Monorepo: Deprecation Cleanup Work

### PR DESCRIPTION
**Pull request by holgerd77**
Deprecation cleanup work for the upcoming breaking releases.

Will track the changes in the following list:

- Common: remove deprecated `nextHardforkBlock()`, `isNextHardforkBlock()` and `isHardforkBlock()` methods
- Blockchain: remove deprecated `getHead()` method
- EVM: rename SHA3 opcode -> KECCAK256
- EVM: rename DIFFICULTY opcode to PREVRANDAO post Merge

### CODE REVIEW

**Review by jochem-brouwer — DISMISSED** [review]
LGTM!

I am also super happy with df49a2344266032b0f8f62fb508223612d5717e4, great that this works, and love the test!!

**Review by g11tech — DISMISSED** [review]
lgtm!

**Comment by holgerd77** [comment]
@jochem-brouwer @g11tech thanks for the reviews, some tests still failing though, will have a look.

**Comment by jochem-brouwer** [comment]
Ah, I know - it is because we dont have PREVRANDAO gas costs :)

**Review by jochem-brouwer — APPROVED** [review]
Great, LGTM!

**Pull request merged**
