### PR TITLE
ci: fix failing node 16

### LINKED ISSUE #1341: Monorepo: Node 16 Tests failing
The nightly Node tests are [failing](https://github.com/ethereumjs/ethereumjs-monorepo/runs/3024683130?check_suite_focus=true) for Node 16, this should be investigated and fixed.

### PR DESCRIPTION
**Pull request by ryanio**
Fixes #1341 

The cause seems to be a new release of `libp2p-crypto` where a new module `multiformats` is added (https://github.com/libp2p/js-libp2p-crypto/commit/94966df10f86e3844363780873f03518138cf874)

My initial hunch is that we don't have an updated `package-lock` so it's pulling an old instance of the dependency cache and failing to resolve the module.

### CODE REVIEW

**Comment by acolytec3** [comment]
That's what I was thinking too though it failed again and it looks like it's still trying to import the hold dependency.  Any tricks to making it accept the new `package-lock.json?

**Comment by ryanio** [comment]
> That's what I was thinking too though it failed again and it looks like it's still trying to import the hold dependency. Any tricks to making it accept the new `package-lock.json?

yes the key of the cache is a hash of the package-lock.json files which is very cool (see [here](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/.github/workflows/vm-build.yml#L31))

I discovered these new lint errors last week but since we haven't had a full refresh of the package-lock it hasn't showed up in the ci until now. added a commit to fix.

**Comment by ryanio** [comment]
ok now failing at the real error, it's stuck on karma:

> ERROR [karma-server]: Error: Unable to resolve module [multiformats/hashes/sha2] from [/home/runner/work/ethereumjs-monorepo/ethereumjs-monorepo/node_modules/libp2p-crypto/src/keys/rsa-class.js]

`multiformats/package.json`:
Screen Shot 2021-07-12 at 5 45 10 PM

I do have a `multiformats/esm/src/hashes/sha2-browser.js` in my local 🤔

**Comment by ryanio** [comment]
Adding this alias hotifx to karma seemed to fix it :) https://github.com/ethereumjs/ethereumjs-monorepo/pull/1346/commits/dfd38ffbbab0a14048c450098fec06999978c5cb

**Review by acolytec3 — APPROVED** [review]

**Comment by holgerd77** [comment]
@ryanio thanks for taking this on! 😄 

Node 16 [broke again](https://github.com/ethereumjs/ethereumjs-monorepo/runs/3062357366?check_suite_focus=true) during last night run though, not sure, is this a new respectively yet another issue? 😛

Argh. 🙂

**Comment by acolytec3** [comment]
@holgerd77 It was a networking issue again.  I saw that before but just some sort of connectivity thing.  I just re-ran the jobs and they all passed.  :shrug:

**Comment by holgerd77** [comment]
Ah ok, thanks.

**Comment by ryanio** [comment]
@acolytec3 thanks for re-running! was happy to see the green checkmark this morning :) could you share that network connectivity error here next time you see it again? i'd like to see what it is and see if we can make it more reliable.

**Comment by acolytec3** [comment]
```
lerna info hoist Finished pruning hoisted dependencies
lerna ERR! npm install --ignore-scripts exited 1 in 'root'
lerna ERR! npm install --ignore-scripts stderr:
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! network Invalid response body while trying to fetch https://registry.npmjs.org/sha.js: aborted
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
```

I'm not sure what to make of this other than 'the network timed out'. I'll watch it again tonight and see what happens

**Comment by acolytec3** [comment]
I didn't touch it this time 😀. I guess we'll just keep an eye on it. I'm gonna close the issue for now.

**Pull request merged**
