### PR TITLE
Minimal `rlpx` test suite

### PR DESCRIPTION
**Pull request by acolytec3**
- Adds a minimal test suite for the `rlpx` class, with much help from CodiumAI robots
- Fixes devp2p so it pushes code coverage reports again

### CODE REVIEW

**Comment by acolytec3** [comment]
Looks like devp2p test coverage isn't being uploaded to CodeCoverage for some reason but here's what `c8` says about coverage increase:
On current `master`
image

On this pr
image
So, somewhat better.

**Comment by holgerd77** [comment]
Updated this via UI

**Comment by holgerd77** [comment]
Updated this via UI

**Review by holgerd77 — APPROVED** [review]
These are fantastic new tests I will take as some reference tests for myself from now on how to deal with this vi mocking, super great and insightful! 🤩

Will merge.

**Pull request merged**
