### PR TITLE
client/sync: return Promise.race() instead of async-promise-executor

### PR DESCRIPTION
**Pull request by ScottyPoi**
similar to #3015.  Rewrites `sync()` without the `async-promise-generator` api.

--

The Promise returned at the end of the original code was designed to resolve **either** when a SYNC_SYNCHRONIZED event is emitted **or** when `await _fetcher.fetch()` return/throws.

This was done using an **async-promise-executor**:
`  return new Promise( async (res, rej) => { ... } ) `

This is generally considered an anti-pattern, and violated our eslint rules, requiring an ignore comment.

--
Refactored by breaking `sync()` up into smaller methods: `sync()`, `syncWithFetcher()`, and `resolveSync()`, and returning `Promise.race([...])` instead of the async promise executor.

1. `resolveSync()` externalized to `this.resolveSync()`
`resolveSync()` is called as a final step to clear the fetcher and emit a debug log.  This was defined inside of the `sync()` function, but is now defined independently.

2. `syncWithFetcher`
The internal `try/catch` block that contains `await this._fetcher.fetch()`.  Now externalized to an external method `this.syncWithFetcher()`.

3. `syncEvent`
The `SYNC_SYNCHRONIZED` event that can resolve `sync()` is now defined as a Promise.

4. Return Promise
`sync()` now returns `Promise.race([this.syncWithFetcher(), syncEvent])`.  Resolving through whichever happens first.

### CODE REVIEW

**Comment by holgerd77** [comment]
Updated this via UI

**Comment by ScottyPoi** [comment]
> Seems one client test might be failing here repeatedly, so this is eventually related to the change done and needs some investigation.

The `fullsync.spec.ts` test was failing after the initial commits, even though all other `sync` related unit and integration tests were passing.  Investigating led me to believe that this was indeed a flaw in the refactor.

More explanation in the PR description above

**Comment by ScottyPoi** [comment]
```
 FAIL  test/sync/beaconsync.spec.ts [ test/sync/beaconsync.spec.ts ]
 FAIL  test/sync/fetcher/reverseblockfetcher.spec.ts [ test/sync/fetcher/reverseblockfetcher.spec.ts ]
TypeError: Class extends value undefined is not a constructor or null
 ❯ src/sync/lightsync.ts:17:40
     15|  * @memberof module:sync
     16|  */
     17| export class LightSynchronizer extends Synchronizer {
       |                                        ^
     18|   constructor(options: SynchronizerOptions) {
     19|     super(options)
 ❯ src/service/lightethereumservice.ts:2:31
 ❯ src/service/index.ts:3:31

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/5]⎯

 FAIL  test/sync/lightsync.spec.ts [ test/sync/lightsync.spec.ts ]
 FAIL  test/sync/snapsync.spec.ts [ test/sync/snapsync.spec.ts ]
 FAIL  test/sync/sync.spec.ts [ test/sync/sync.spec.ts ]
TypeError: Class extends value undefined is not a constructor or null
 ❯ src/sync/beaconsync.ts:28:41
     26|  * @memberof module:sync
     27|  */
     28| export class BeaconSynchronizer extends Synchronizer {
       |                                         ^
     29|   skeleton: Skeleton
     30|   private execution: VMExecution
 ❯ src/sync/index.ts:1:31
 ❯ src/service/fullethereumservice.ts:11:3
 ```

**Comment by holgerd77** [comment]
@g11tech could you give this here a quick review? I think you are better on judging on the implications of this, I am always struggling with all-things-promises.

**Comment by holgerd77** [comment]
Updated this via UI

**Review by acolytec3 — APPROVED** [review]
Great clean-up.

**Review by g11tech — APPROVED** [review]
lgtm great cleanup :heart:

**Pull request merged**
