### PR TITLE
Stop throwing when non-hex-prefixed addresses are passed to util `isValid..` methods

### PR DESCRIPTION
**Pull request by cgewecke**
PR changes `isValidAddress`, `isValidChecksumAddress` and `isZeroAddress` to return `false` when given a non-hex-prefixed string (or non-string) input.

This proposal comes from a Hardhat integration [review discussion][1]. 

Basic idea is that it's unexpected behavior for boolean validators like this to throw. 

[1]: https://github.com/nomiclabs/hardhat/pull/1337#discussion_r600056630

### CODE REVIEW

**Comment by ryanio** [comment]
reasoning seems valid to me, although would this be considered a breaking change for existing usage?

**Comment by alcuadrado** [comment]
> reasoning seems valid to me, although would this be considered a breaking change for existing usage?

I think it can be seen as a bugfix that won't lead to breaking code unless you were doing something extremely weird. My reasoning is that you already have to handle both `false` and an exception, and they both had the same semantics, so they should be doing the same.

**Comment by ryanio** [comment]
sounds good, @cgewecke do you mind adding a changelog entry

**Comment by cgewecke** [comment]
@ryanio Updated! Thanks.

**Review by ryanio — APPROVED** [review]
lgtm!

**Pull request merged**
