### PR TITLE
chore: fix documentation building

### PR DESCRIPTION
**Pull request by faustbrian**
> Fixes https://github.com/ethereumjs/ethereumjs-monorepo/issues/1779

Added `typedoc` as a dependency at the root and removed it from every package to make sure a consistent version is used. Ran `npm run docs:build --workspaces` to regenerate them.

### CODE REVIEW

**Review by acolytec3 — DISMISSED** [review]
LGTM.  Only question is does it make sense to add a monorepo level `docs` script to just regenerate all of them at once?  I don't have a strong opinion here but thought it could be helpful

**Comment by acolytec3** [comment]
Cool, hopefully rebasing this will be easy with the new prettier script. Let me know once rebased and I'll approve so we can knock this out too.

**Review by acolytec3 — APPROVED** [review]
Lgtm

**Comment by holgerd77** [comment]
Nice, thanks a lot! Really cool PR, `typedoc` consolidation in root package.json is also pretty good, didn't realize that we still had this redundant.

**Pull request merged**
