### PR TITLE
common: add calaveras

### PR DESCRIPTION
**Pull request by ryanio**
This PR adds the latest ephemeral testnet chain [Calaveras](https://github.com/ethereum/eth1.0-specs/blob/master/network-upgrades/client-integration-testnets/calaveras.md) to common.

### CODE REVIEW

**Comment by ryanio** [comment]
My first runs on the client are unsuccessful with a subprotocol error, although the STATUS debug message seems accurate, can someone else give the client a run with `DEBUG=devp2p* npm run client:start -- --network=calaveras` and see if the chain starts syncing?

```
devp2p:rlpx:peer Received HELLO (message code: 0 - 0 = 0) 3.9.20.133:30303 +0ms
  devp2p:rlpx:peer Send HELLO to 3.9.20.133:30303 +1ms
  devp2p:rlpx handshake with 3.9.20.133:30303 was successful (peer eip8 ack) +1ms
  devp2p:eth Send STATUS message to 3.9.20.133:30303 (eth65): [V:65, NID:123, TD:1, BestH:eb9233d, GenH:eb9233d, ForkHash: 0x49f2f6b6, ForkNext: 500] +2ms
  devp2p:rlpx:peer Received header 3.9.20.133:30303 +302ms
  devp2p:rlpx:peer Received body 3.9.20.133:30303 01c110 +0ms
  devp2p:rlpx:peer Received DISCONNECT (message code: 1 - 0 = 1) 3.9.20.133:30303 +0ms
  devp2p:rlpx:peer DISCONNECT reason: SUBPROTOCOL_ERROR 3.9.20.133:30303 +0ms
```

I've run into `SUBPROTOCOL_ERROR` on my local before in other unrelated runs, so I am not sure if it might just be me.

**Comment by holgerd77** [comment]
Your fork hashes are wrong, you need to calculate with:

```typescript
import Common from './src'
let c = new Common({ chain: 'calaveras' })
c._calcForkHash('chainstart') // '0xe34c4aff'
```

And so on...

**Comment by ryanio** [comment]
ah thanks, I actually wrote a little script to do that and was surprised it outputted the same fork hashes as baikal, I'll check my code when I'm back on my computer and add a commit to fix.

**Comment by ryanio** [comment]
great thanks again @holgerd77, updating those fork hashes got me syncing :)
cool to see the
`Execution hardfork switch on block number=500 hash=e96eae6d... old=berlin new=london`
and no hiccups with the tx heavy blocks on the transition

Screen Shot 2021-06-07 at 8 48 36 PM

**Comment by ryanio** [comment]
have gotten stuck at block 2100 twice now from fresh starts.

i restarted with devp2p debug and stuck in a loop of...

```
  devp2p:eth Send GET_BLOCK_BODIES message to 3.9.20.133:30303: f90672a0ed0b123b93c05771ae8c842746e3b28899515c1a7804b27e3e9a... +5ms
  devp2p:rlpx:peer Received header 3.9.20.133:30303 +150ms
  devp2p:rlpx:peer Received body 3.9.20.133:30303 16f896c2c0c0c2c0c0c2c0c0c2c0c0c2c0c0c2c0c0c2c0c0c2c0c0c2c0c0... +1ms
  devp2p:rlpx:peer Received undefined (message code: 22 - 16 = 6) 3.9.20.133:30303 +0ms
  devp2p:eth Received BLOCK_BODIES message from 3.9.20.133:30303: f896c2c0c0c2c0c0c2c0c0c2c0c0c2c0c0c2c0c0c2c0c0c2c0c0c2c0c0c2... +0ms
  devp2p:eth Send GET_BLOCK_HEADERS message to 3.9.20.133:30303: c6820961328080 +8ms
  devp2p:rlpx:peer Received header 3.9.20.133:30303 +302ms
  devp2p:rlpx:peer Received body 3.9.20.133:30303 14f9762af9025aa05d1fa361b99666d14dd6c81903bfcc4b69cab3d5b250... +5ms
  devp2p:rlpx:peer Received undefined (message code: 20 - 16 = 4) 3.9.20.133:30303 +0ms
  devp2p:eth Received BLOCK_HEADERS message from 3.9.20.133:30303: f9762af9025aa05d1fa361b99666d14dd6c81903bfcc4b69cab3d5b250ad... +0ms
  devp2p:eth Send GET_BLOCK_BODIES message to 3.9.20.133:30303: f90672a083873023d95be49a561e0351faf35202fc1aa4f92978e44a428d... +4ms
  devp2p:rlpx:peer Received header 3.9.20.133:30303 +153ms
  devp2p:rlpx:peer Received body 3.9.20.133:30303 16f896c2c0c0c2c0c0c2c0c0c2c0c0c2c0c0c2c0c0c2c0c0c2c0c0c2c0c0... +1ms
  devp2p:rlpx:peer Received undefined (message code: 22 - 16 = 6) 3.9.20.133:30303 +0ms
  devp2p:eth Received BLOCK_BODIES message from 3.9.20.133:30303: f896c2c0c0c2c0c0c2c0c0c2c0c0c2c0c0c2c0c0c2c0c0c2c0c0c2c0c0c2... +0ms
```

it seems fine as it receives headers and bodies but also `Received undefined`, and no blocks actually syncing. no errors output from our libs or anything. it would be cool to see what blocks are actually being requested and returned (although I'm wary of more string interpolation these days 😄). i am also only connected to one peer `3.9.20.133`.

**Review by holgerd77 — APPROVED** [review]
Have tested this locally, this now works fine. 😄

**Pull request merged**
