### PR TITLE
Add London+ hardfork support for Retesteth, fix EIP150 tests

### PR DESCRIPTION
**Pull request by jochem-brouwer**
This PR:

- Ensures we run correctly on London+ hardforks. We always defaulted to base fee 7, while most tests have different base fee.
- Fixes EIP150 tests by ensuring if tx fails, coinbase account is still touched and cleaned up if necessary.

### CODE REVIEW

**Comment by holgerd77** [comment]
Rebased this via UI.

**Review by holgerd77 — APPROVED** [review]
LGTM

**Comment by jochem-brouwer** [comment]
Thanks for the rebase @holgerd77, will merge. CC @winsvega

**Comment by winsvega** [comment]
Aha. Looks like this one failed the tests with invalid transactions in state tests.

Ethereumjs return different postate hash and different logs hash. 

http://retesteth.ethdevops.io/results/log//2023-05-05-1683267268-ethereumjs.txt

**Pull request merged**
