### PR TITLE
Monorepo: fix broken eth.wiki links

### PR DESCRIPTION
**Pull request by gabrocheleau**
This PR fixes broken eth.wiki links where possible. And removes the few instances where corresponding docs couldn't be found.

### CODE REVIEW

**Review by jochem-brouwer — COMMENTED** [review]
Mega nit: some URLs end with `/` while others do not. Could you make it consistent?

**Review by acolytec3 — APPROVED** [review]
LGTM

**Comment by gabrocheleau** [comment]
> Mega nit: some URLs end with `/` while others do not. Could you make it consistent?

Sure :) will do tomorrow morning

**Review by holgerd77 — APPROVED** [review]
LGTM

**Pull request merged**
