### PR TITLE
ci: fix hardhat e2e resolutions

### PR DESCRIPTION
**Pull request by ryanio**
The hardhat e2e setup is not picking up the new ethereumjs deps and I found that the resolutions need to be added to the [root package.json](https://github.com/yarnpkg/yarn/issues/5039#issuecomment-880166818).

### CODE REVIEW

**Comment by acolytec3** [comment]
Ah, I think I remember that from my attempts to get it working. I guess I missed that in your final iteration on the PR.

**Comment by ryanio** [comment]
> Ah, I think I remember that from my attempts to get it working. I guess I missed that in your final iteration on the PR.

yeah oops sorry about that, I think while I was trying to fix/refactor I updated it to hardhat-core's package.json when I saw the deps listed in there.

**Comment by acolytec3** [comment]
So maybe this job is working as intended now. I'm seeing compile errors specific to our libraries around the `stateManager` now. That's promising.

**Comment by ryanio** [comment]
> So maybe this job is working as intended now. I'm seeing compile errors specific to our libraries around the `stateManager` now. That's promising.

yes although it's a different error, I'm having trouble because if we put `ethereumjs-util` in the `resolutions` then it will overwrite the older `eth-sig-util` use of `ethereumjs-util v5` and causes these errors we've seen before ([here](https://github.com/ethereumjs/ethereumjs-monorepo/runs/3237299405#step:9:3356)):

```
1) Local accounts provider
       eth_signTypedData_v4
         Should be compatible with EIP-712 example:
     Error: This method only supports Buffer but input was: EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)
      at Object.exports.assertIsBuffer (/home/runner/work/ethereumjs-monorepo/ethereumjs-monorepo/hardhat/node_modules/ethereumjs-util/src/helpers.ts:21:11)
      at Object.exports.keccak (/home/runner/work/ethereumjs-monorepo/ethereumjs-monorepo/hardhat/node_modules/ethereumjs-util/src/hash.ts:13:3)
      at Object.hashType (/home/runner/work/ethereumjs-monorepo/ethereumjs-monorepo/hardhat/node_modules/eth-sig-util/src/index.ts:267:20)
```

so I tried skipping `ethereumjs-util` as a test (although would be nice to have it) but then getting a weird type mismatch from it picking up `node_modules/ethereumjs-util` as well as `node_modules/@ethereumjs/block/node_modules/ethereumjs-util` (although these files should be the same as they haven't changed, the differing locations seems to be triggering it?) [here](https://github.com/ethereumjs/ethereumjs-monorepo/pull/1391/checks?check_run_id=3243356722#step:9:343):

> Type 'Promise<import("/home/runner/work/ethereumjs-monorepo/ethereumjs-monorepo/hardhat/packages/hardhat-core/node_modules/ethereumjs-util/dist/account").Account>' is not assignable to type 'Promise<import("/home/runner/work/ethereumjs-monorepo/ethereumjs-monorepo/hardhat/node_modules/**@ethereumjs/block/node_modules/ethereumjs-util**/dist/account").Account>'.

> `├─ @ethereumjs/block@3.5.0`
> `│  └─ ethereumjs-util@7.2.0`

which patricio has pointed out would be solved by using peerDependencies, although that's a breaking change itself and peerDependencies typically don't install by default so it adds a step to the install process.

I'm still thinking/working on a solution for this ci, will probably test some ideas out.

**Comment by ryanio** [comment]
I think using `resolutions` is overreaching since it is exceeding max major version ranges specified, e.g.:

```
yarn list v1.22.11
warning Resolution field "ethereumjs-util@7.2.0" is incompatible with requested version "ethereumjs-util@^5.1.1"
warning Resolution field "ethereumjs-util@7.2.0" is incompatible with requested version "ethereumjs-util@^6.0.0"
warning Resolution field "merkle-patricia-tree@4.3.0" is incompatible with requested version "merkle-patricia-tree@3.0.0"
warning Resolution field "ethereumjs-util@7.2.0" is incompatible with requested version "ethereumjs-util@^6.0.0"
warning Resolution field "ethereumjs-util@7.2.0" is incompatible with requested version "ethereumjs-util@^6.0.0"
warning Resolution field "ethereumjs-util@7.2.0" is incompatible with requested version "ethereumjs-util@^5.0.0"
warning Resolution field "merkle-patricia-tree@4.3.0" is incompatible with requested version "merkle-patricia-tree@^2.1.2"
```

Ideally we would do something like `"ethereumjs-util@^7.0.0": "7.2.0"` but that doesn't seem to be supported yet (https://github.com/yarnpkg/yarn/issues/5794).

I'm surprised more things didn't break! The only thing that seems to be tripping up is the ethereumjs-util change to only accept Buffers over strings.

My next thought is instead of using resolutions what if we just upgrade the direct ethereumjs deps in `hardhat-core/package.json`, that seems like a more reasonable approach now knowing that the resolutions behavior is to overwrite all sub-deps regardless of major version range. So this way only the direct deps used in the hardhat code should be upgraded to latest. I'll give it a try.

**Comment by ryanio** [comment]
great! I have this working now. The new deps are correctly being proxied and I tested this by adding a commit that adds a new method to the statemanger interface and that failed during hardhat's e2e build with a type mismatch (```Property 'someNewlyAddedBreakingMethod' is missing in type 'ForkStateManager' but required in type 'StateManager'.```). this would have caught the v5.5.1 bug :|

**Comment by acolytec3** [comment]
Pending a clean pass from these CI jobs. This looks good! Great work!

**Comment by ryanio** [comment]
> Pending a clean pass from these CI jobs. This looks good! Great work!

thanks! I'll merge in

**Pull request merged**
