### PR TITLE
Monorepo: Develop Branch Rebase Test 2022-03-24

### PR DESCRIPTION
**Pull request by holgerd77**
Rebase test of the `develop` branch, do not merge.

### CODE REVIEW

**Comment by holgerd77** [comment]
Ok, I've done *a lot* of fixes, will stop here for today.

It would be really really great if someone could pick this up today - maybe @ryanio or @g11tech - there are some tests in the client failing but otherwise this should hopefully be fine (maybe have a second look though, so many fixes to be done).

Otherwise we likely wouldn't get this pushed any more before my holidays.

Thanks! 🙂

**Comment by holgerd77** [comment]
(in doubt just directly push here on that branch up to a state where CI passes, DO NOT MERGE HERE THOUGH, also, note for reviewers: rather just "approve" just by dropping a comment and not by giving a REAL approval for security reasons)

**Comment by acolytec3** [comment]
This should be good to go, all tests are passing now.

**Comment by holgerd77** [comment]
Thanks a lot! 🙏🙂

**Comment by holgerd77** [comment]
Ok, this has now been pushed to be the latest state of `develop`, will close here.

**Pull request closed without merging**
