### PR TITLE
Prague test fixtures runner instructions

### PR DESCRIPTION
**Pull request by jochem-brouwer**
**This PR is not intended to get merged, but for instructions only**

This PR describes how to run Prague fixtures, taken from https://github.com/ethereum/execution-spec-tests

For instance, these 2537 tests: https://github.com/ethereum/execution-spec-tests/files/15099569/fixtures_develop.tar.gz

- Download the fixtures
- Put the blockchain tests in a directory inside `./packages/ethereum-tests` (for instance EIP2537)
- Now from `./packages/vm`:
- `npm run test:blockchain -- --fork=Prague --dir=../EIP2537`

For 2537:

```
1..1099
# tests 1099
# pass  935
# fail  164
```

### CODE REVIEW

**Comment by acolytec3** [comment]
I think we can safely close this one as I've incorporated these changes into #3393

**Comment by jochem-brouwer** [comment]
In your branch the tests do not run out of the box for me, have to add 

```
      {
        name: 'prague',
        block: null,
      }
```

To chains.ts (in mainnet)

**Comment by acolytec3** [comment]
:thinking: lemme look again.  I hope I didn't miss that in the updated branch I merged to master.

**Comment by jochem-brouwer** [comment]
Never mind!! Forgot to pull latest master - woops, sorry!

**Pull request closed without merging**
