### PR TITLE
Remove unused deps

### PR DESCRIPTION
**Pull request by paulmillr**
#2193

Before: `audited 1939 packages`, after: `1585 packages`

1. Why is `lib` used instead of `src` in `client`? I have ignore rules for `lib` dirs, because they contain compiled js code all of the time.
2. `verdaccio@4` is the only package, it seems, that requires downloading node.js binaries/headers from nodejs.org site. Does it make sense to extract it to a separate directory? Or, would you rather keep it top-level, to be installed in all cases? UPD: v5 seems to be ok. also v4 has security warnings

### CODE REVIEW

**Comment by holgerd77** [comment]
On 1. Historical inconsistency
Can be changed, but please in a separate PR

**Comment by holgerd77** [comment]
Side note: it's very much ok if this task will take 6 weeks or so, you do not have to finish this all in one go. 😆

Maybe we can also merge something in in-between and split this up into some rounds.

**Comment by acolytec3** [comment]
> 2\. `verdaccio@4` is the only package, it seems, that requires downloading node.js binaries/headers from nodejs.org site. Does it make sense to extract it to a separate directory? Or, would you rather keep it top-level, to be installed in all cases? UPD: v5 seems to be ok. also v4 has security warnings


As far as I know, verdaccio is only used in one CI script (specifically for the hardhat e2e tests that we were running as a sanity check when pushing changes to verify if they were breaking or not) so it ought to be removable from the top level package.json entirely.  Let me try that in my branch that updates the hardhat tests and see if it still works.

>@acolytec3 do you know what specific issue required adding karma-typescript-es6-transform in https://github.com/ethereumjs/ethereumjs-monorepo/pull/2091?

Unless something has changed, Karma doesn't support ES6 so uses Babel to transpile to ES5 compatible code - https://github.com/monounity/karma-typescript/tree/master/packages/karma-typescript-es6-transform

Looks like removing that transform is what is causing those client tests to fail.  I had to add that in to get karma to work for client tests since it depends on an ESM module in the imports.

**Comment by paulmillr** [comment]
I've ensured all devDependencies in root package have specific versions.

1. A broken typescript, prettier, or anything else — could bring malware to the compiled code, before packages are published.
2. I have went through package-lock.json to ensure there are no duplicates and that specified versions are OK
3. This change should have no effect on client code, since it's only devDependencies. We will think if it would make sense to fixate prod deps in the next major release, and i'm not sure if it would make sense at all. Keeping devDeps the new way is a good thing and security improvement in any case.

**Comment by acolytec3** [comment]
Also, depending on how this [CI run](https://github.com/ethereumjs/ethereumjs-monorepo/runs/7925155491?check_suite_focus=true) goes, we may be able to remove verdaccio from the deps as well.

**Comment by acolytec3** [comment]
@paulmillr looks like Verdaccio still works if we just install it directly in that CI script.  You should be able to remove it from the dependencies here since we're not currently running the hardhat tests at all (since they're broken).

**Comment by holgerd77** [comment]
> @paulmillr looks like Verdaccio still works if we just install it directly in that CI script. You should be able to remove it from the dependencies here since we're not currently running the hardhat tests at all (since they're broken).

Oh, that's great, actually the most significant share of the dependency alert noise is coming from Verdaccio! 🙏 🎉

**Comment by paulmillr** [comment]
The PR is ready now.

**Comment by paulmillr** [comment]
@faustbrian i've tried this, see earlier commits, there is additional more complicated logic in fs-extra, so maybe in the next pr

**Review by acolytec3 — APPROVED** [review]
Yay for less deps.

**Comment by holgerd77** [comment]
@paulmillr congrats to the substantial achievements here! 💯

Great to see this merged! 🙂

**Pull request merged**
