### PR TITLE
4844 Browser Readiness Releases

### PR DESCRIPTION
**Pull request by holgerd77**
Follow-up on #3261 

This is a (relatively big) release round following relatively shortly after the main Dencun hardfork releases.

Biggest addition is the integration of the [kzg-wasm](https://github.com/ethereumjs/kzg-wasm) library (together with an also browser-compatibility-affecting trie bug) which now makes all 4844 functionality fully browser compatible! 🎉

### CODE REVIEW

**Review by acolytec3 — DISMISSED** [review]
LGTM

**Comment by holgerd77** [comment]
Please do not merge yet, this still needs to be updated with the KZG changes!

**Review by jochem-brouwer — COMMENTED** [review]
Some small comments

**Review by jochem-brouwer — APPROVED** [review]
LGTM assuming CI passes

**Review by gabrocheleau — APPROVED** [review]

**Comment by holgerd77** [comment]
Just published the following releases on npm:

- `@ethereumjs/util` [v9.0.3](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Futil%409.0.3)
- `@ethereumjs/common` [v4.3.0](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fcommon%404.3.0)
- `@ethereumjs/trie` [v6.2.0](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Ftrie%406.2.0)
- `@ethereumjs/tx` [v5.3.0](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Ftx%405.3.0)
- `@ethereumjs/devp2p` [v6.1.2](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fdevp2p%406.1.2)
- `@ethereumjs/wallet` [v2.0.3](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fwallet%402.0.3)
- `@ethereumjs/verkle` [v0.0.2](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fstatemanager%400.0.2)
- `@ethereumjs/statemanager` [v2.3.0](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fstatemanager%402.3.0)
- `@ethereumjs/block` [v5.2.0](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fblock%405.120)
- `@ethereumjs/ethash` [v3.0.3](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fethash%403.0.3)
- `@ethereumjs/genesis` [v0.2.2](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fgenesis%400.2.2)
- `@ethereumjs/blockchain` [v7.2.0](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fblockchain%407.2.0)
- `@ethereumjs/evm` [v3.0.0](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fevm%403.0.0)
- `@ethereumjs/vm` [v8.0.0](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fvm%408.0.0)
- `@ethereumjs/client` [v0.10.1](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fclient%400.10.1)

**Pull request merged**
