### PR TITLE
VM: debug tools

### PR DESCRIPTION
**Pull request by jochem-brouwer**
Debug tools for VM which helps debugging consensus bugs.

### CODE REVIEW

**Comment by holgerd77** [comment]
Ah, I am actually not sure what you are doing here, why do you want to merge these heavy bug-specific stack traces into master? And can we eventually stay in the `scripts` folder and not add just another folder `tools`here + can you please add a one-line in `developer.md` on usage? Thanks!

**Comment by holgerd77** [comment]
(if you just want to distribute the stack traces maybe simply put in a gist? I think we shouldn't use master to arbitrarily root some stuff temporarily)

**Comment by jochem-brouwer** [comment]
Just to clarify; I am not sure if I want to merge this tool, but just wanted to share it in case it is handy for these consensus bugs. You are right that we should not dump in raw JSON traces into the master branch.

**Comment by holgerd77** [comment]
Ah, thanks for the update! 😄  👍

**Comment by jochem-brouwer** [comment]
Will close since I don't have the intention to merge this.

**Pull request closed without merging**
