### PR TITLE
evm: add new exports requested by hardhat

### LINKED ISSUE #2062: Add new exports needed for Hardhat
Hardhat requested we export the following items from the `evm` as part of the final breaking release
- `ERROR` enum
- `ExecResult`
- `InterpreterStep`
- `Message`

### PR DESCRIPTION
**Pull request by acolytec3**
Fixes #2062

### CODE REVIEW

**Comment by paulmillr** [comment]
Can't they just import the files themselves instead of index.ts?

**Comment by acolytec3** [comment]
> Can't they just import the files themselves instead of index.ts?

@alcuadrado Can you or someone from your team comment here?  I don't see an issue with us adding these as toplevel exports since I believe you were having to import them from `@etheremjs/evm/dist/...` which was kind of hideous.

@paulmillr Is there a reason for keeping these out of the top level exports?

**Comment by paulmillr** [comment]
@acolytec3 reason is simple: tree shaking. For example, [this](https://github.com/paulmillr/noble-hashes/tree/main/src) has 10 files, if a user wants one, they import one; other files won't be included into the build; which will make the result file much smaller.

**Comment by acolytec3** [comment]
> Can't they just import the files themselves instead of index.ts?

Got it.  I'm not decrying the value of tree-shaking but that would be a complete departure from how we do exports right now and I wouldn't want to start piecemeal changing our approach. 

Beyond that, if we're going to go the route you suggest, would it make more sense to use an `exports` directive in `package.json` and define all the export paths that way?

**Comment by paulmillr** [comment]
Yeah, better keep the approach as-is before the release.

> and define all the export paths that way

I think you will need to do this in any case in order to support common.js + esm at the same time.

**Comment by acolytec3** [comment]
@alcuadrado @fvictorio  So any opinion whether to add these imports or do want to leave them where they were and we can maybe go the route of adding import directives in the package.json?

**Comment by holgerd77** [comment]
Please label

**Comment by holgerd77** [comment]
I think if we have users which need theses imports it makes a lot of sense to add respectively we should do.

**Review by g11tech — APPROVED** [review]
LGTM!

**Comment by fvictorio** [comment]
> I think can do the deep imports, and @fvictorio was mostly worried about importing from '/dist/'. Can you confirm, Franco?

Sorry, I just saw this, but yes, I confirm.

**Comment by acolytec3** [comment]
> > I think can do the deep imports, and @fvictorio was mostly worried about importing from '/dist/'. Can you confirm, Franco?
> 
> Sorry, I just saw this, but yes, I confirm.

Okay, for now, they've been added to the top level import.  Obviously, this could be reworked if needed along the way.

**Pull request merged**
