### PR TITLE
Hardhat e2e test integration

### LINKED ISSUE #1342: Monorepo: Run Hardhat E2E Tests
Hardhat now broke along two releases we have done, the latest on the `@ethereumjs/tx`[v3.3.0](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Ftx%403.3.0) release where there needed to be a hotfix which then was applied here https://github.com/nomiclabs/hardhat/pull/1641.

Both breakages would likely be able to have been prevented with running Hardhat E2E tests, so we should prioritize an integration. E2E tests have been first introduced by @cgewecke in #1134 on a selected third party target (https://github.com/NoahZinsmeister/as-you-permit) (note that the intial description of the PR is misleading since we first had a somewhat differing goal (run/test old EthereumJS library versions in the VM) and then switched over to the goal of testing third-party upstream libraries (like Hardhat) within the context of our libraries as they currently are on `master` respectively a new PR towards `master`).

This initial E2E target needed to be disabled (see #1284) since it wasn't reliable. We nevertheless can take this first work as a blueprint respectively the whole integration as a basis to integrate Hardhat E2E tests.

Depending on the CI run times added these kind of tests might to be run along a PR or alternatively also as nightly tests (like the Node tests, see [node-versions.yml](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/.github/workflows/node-versions.yml) as reference for an integration).

After having integrated Hardhat (or parts of the Hardhat tests) it might also make sense to expand to other libraries (e.g. Web3.js), just as some side note.

//cc @alcuadrado @fvictorio

### PR DESCRIPTION
**Pull request by acolytec3**
Will fix #1342 once closed.

### CODE REVIEW

**Comment by ryanio** [comment]
I was able to get all tests passing locally, did some clean up on the scripts, and refactored the hardhat lines out to `scripts/e2e-hardhat.sh` with some additional debugging lines that will hopefully help isolate future issues.

Going to see how the CI does now with this run.

I also rebased on master and did a force push.

**Comment by ryanio** [comment]
Ok only [10 tests failing left](https://github.com/ethereumjs/ethereumjs-monorepo/pull/1348/checks?check_run_id=3120197684#step:7:3096), all with similar regex match errors, not sure what it means yet:

```
10 failing

  1) Provider logs
       Hardhat Network provider
         automine enabled with pending txs
           one pending tx, sent tx at the end of the block:
     AssertionError: expected '    Transaction: 0x66576a395158d9efd6b67b3713c216a622bb156bff8e8bf595f4b034eb73c9d7' to match /^    Transaction:\s+\u001b[1m0x[0-9a-f]{64}/
      at Context.<anonymous> (test/internal/hardhat-network/provider/logs.ts:407:20)
```

**Comment by acolytec3** [comment]
@ryanio Looks like this is passing now.  Thanks for all the fixes!  Are we ready to merge at this point?  I'm thinking we'll need to update the workflow triggers to remove the run on pushes to this branch or whatever it is.

**Comment by ryanio** [comment]
great, thanks for that last fix!

This is our typical trigger setup which I've included in the workflow:

```yml
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    types: [opened, reopened, synchronize]
```

**Comment by acolytec3** [comment]
@ryanio Cool, can you approve so we can merge?  I can't approve my own PR ;-)

**Review by ryanio — APPROVED** [review]
lgtm!

**Pull request merged**
