### PR TITLE
devp2p/client: add les v3/v4

### PR DESCRIPTION
**Pull request by ryanio**
This PR fixes `devp2p/examples/peer-communication-les.ts` by upgrading to les v4.

Sample run:

```
➜  examples git:(les-v4) ✗ ts-node peer-communication-les.ts
Add peer: 52.169.42.101:30303 Geth/v1.10.2-unstable-aab35600-20210322/linux-amd64/go1.16.2 (les4) (total: 1)
Add peer: 159.89.28.211:30303 Geth/v1.10.5-unstable-10eb654f-20210623/linux-amd64/go1.16.5 (les4) (total: 2)
----------------------------------------------------------------------------------------------------------
block 8845079 received: 0a3040af08dc247ad9e4290285360b9af0d58b8363c8cd1f0e0832bb2f98630a (from 52.169.42.101:30303)
----------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------
block 8845079 received: 0a3040af08dc247ad9e4290285360b9af0d58b8363c8cd1f0e0832bb2f98630a (from 159.89.28.211:30303)
----------------------------------------------------------------------------------------------------------
```

WIP, now working on adding to the client to start light sync from genesis block.

Current challenge is finding LES peers that don't disconnect with `TOO_MANY_PEERS` (happening for me on ropsten/rinkeby/goerli). When trying the rinkeby bootstrap nodes (which the devp2p example above successfully works), getting a consistent but weird error from both peers `CLIENT_QUITTING`:

```
  devp2p:les Send GET_BLOCK_HEADERS message to 159.89.28.211:30303: c601c401328080 +1s
  devp2p:les Send GET_BLOCK_HEADERS message to 52.169.42.101:30303: c602c433328080 +1ms
  devp2p:rlpx:peer Received header 52.169.42.101:30303 +327ms
  devp2p:rlpx:peer Received body 52.169.42.101:30303 01c108 +0ms
  devp2p:rlpx:peer Received DISCONNECT (message code: 1 - 0 = 1) 52.169.42.101:30303 +0ms
  devp2p:rlpx:peer DISCONNECT reason: CLIENT_QUITTING 52.169.42.101:30303 +0ms
  devp2p:rlpx Restart connection refill .. with selector 0 peers: 1, queue size: 0, open slots: 24 +1ms
  devp2p:rlpx 52.169.42.101:30303 disconnect, reason: CLIENT_QUITTING +0ms
  devp2p:rlpx:peer Received header 159.89.28.211:30303 +82ms
  devp2p:rlpx:peer Received body 159.89.28.211:30303 01c108 +0ms
  devp2p:rlpx:peer Received DISCONNECT (message code: 1 - 0 = 1) 159.89.28.211:30303 +1ms
  devp2p:rlpx:peer DISCONNECT reason: CLIENT_QUITTING 159.89.28.211:30303 +0ms
  devp2p:rlpx 159.89.28.211:30303 disconnect, reason: CLIENT_QUITTING +0ms
```

### CODE REVIEW

**Comment by holgerd77** [comment]
Nice, just some context: `LES` protocol specification is defined [here](https://github.com/ethereum/devp2p/blob/master/caps/les.md).

**Comment by ryanio** [comment]
Thanks to Gary Rong in the geth discord channel I realized that one of my prior fixes (in #1241) added the flow control params to the handshake message which geth perceived our peer as a server so removing this fixed the sync! Only the server should be sending the flowControl params to the peer (so the peer can respect the rate of requests)

Syncing rinkeby via LES 🎉
```
INFO [06-30|17:05:15] Imported headers count=50 number=55 hash=db16f0d4... peers=1
INFO [06-30|17:05:19] Imported headers count=750 number=105 hash=f56dbdef... peers=1
INFO [06-30|17:05:19] Imported headers count=50 number=855 hash=e09f3a75... peers=1
INFO [06-30|17:05:21] Imported headers count=750 number=905 hash=201f1656... peers=1
INFO [06-30|17:05:22] Imported headers count=50 number=1655 hash=73f39c3c... peers=1
INFO [06-30|17:05:23] Imported headers count=50 number=1705 hash=614ed642... peers=1
INFO [06-30|17:05:26] Imported headers count=750 number=1755 hash=1e59ac96... peers=1
INFO [06-30|17:05:26] Imported headers count=50 number=2505 hash=b381ca26... peers=1
INFO [06-30|17:05:28] Imported headers count=750 number=2555 hash=14cd9ce0... peers=1
INFO [06-30|17:05:28] Imported headers count=50 number=3305 hash=2848a50f... peers=1
INFO [06-30|17:05:31] Imported headers count=50 number=3355 hash=c2e0bb69... peers=1
INFO [06-30|17:05:34] Imported headers count=750 number=3405 hash=7beaaab2... peers=1
INFO [06-30|17:05:34] Imported headers count=50 number=4155 hash=98671e12... peers=1
INFO [06-30|17:05:36] Imported headers count=750 number=4205 hash=e4c543bb... peers=1
INFO [06-30|17:05:36] Imported headers count=50 number=4955 hash=7c13d613... peers=1
INFO [06-30|17:05:39] Imported headers count=50 number=5005 hash=12234ae4... peers=1
```

---

I also added an `onlyHeader` option to `block.validate` so during light sync the block validation logic doesn't try to verify `txTrie` and `unclesHash` without having that data.

**Comment by acolytec3** [comment]
@ryanio I was able to start syncing from genesis in light mode on both rinkeby and goerli so looks good.  My one question is I'm still seeing that `peer disconnect, reason: SUBPROTOCOL_ERROR (16)` when running the `peer-communication-les.ts` script occasionally.  Do you think we need to research that any further at this point or are we good to go?  I'm not deep enough on the LES protocol to know for sure.

**Comment by acolytec3** [comment]
> Do you think we need to research that any further at this point or are we good to go? I'm not deep enough on the LES protocol to know for sure.
I talked with @holgerd77 further this morning and I don't think this is an issue.  This looks good and everything seems to work!

**Review by acolytec3 — APPROVED** [review]

**Comment by ryanio** [comment]
great, thanks for looking at it! I will hold off on merging until we get the current pending release out first. Thanks for reviewing!

I will also give it another run today to see if there are still subprotocol errors coming through and why that might be.

**Comment by holgerd77** [comment]
From my side you can merge independently since no code is touched from libraries to be released and I need to update and rebase the release PR anyhow, but as you prefer.

**Pull request merged**
