### PR TITLE
Engine-api: blobs (4844) fixes

### LINKED ISSUE #2838: Hive: engine-blobs tests
To run: 

Checkout this repo+branch: https://github.com/marioevz/hive/tree/engine-api-blobs (note: this is thus a fork from `ethereum/hive`) and build hive. Now run:

`./hive --sim ethereum/engine --sim.limit "engine-blobs/" --client ethereumjs`

Results:

```
INFO[06-28|21:38:48] hiveproxy started                        container=e2143c4ca36f addr=172.17.0.2:8081
INFO[06-28|21:38:48] API: suite started                       suite=0 name=engine-blobs
INFO[06-28|21:38:48] API: test started                        suite=0 test=1 name="Blob Transactions On Block 1, Shanghai Genesis (ethereumjs)"
INFO[06-28|21:38:51] API: client ethereumjs started           suite=0 test=1 container=f947b488
INFO[06-28|21:39:09] API: test ended                          suite=0 test=1 pass=true
INFO[06-28|21:39:09] API: test started                        suite=0 test=2 name="Blob Transactions On Block 1, Cancun Genesis (ethereumjs)"
INFO[06-28|21:39:12] API: client ethereumjs started           suite=0 test=2 container=2c002f07
INFO[06-28|21:39:30] API: test ended                          suite=0 test=2 pass=true
INFO[06-28|21:39:30] API: test started                        suite=0 test=3 name="Blob Transaction Ordering, Single Account (ethereumjs)"
INFO[06-28|21:39:32] API: client ethereumjs started           suite=0 test=3 container=4d8f288a
INFO[06-28|21:39:45] API: test ended                          suite=0 test=3 pass=true
INFO[06-28|21:39:45] API: test started                        suite=0 test=4 name="Blob Transaction Ordering, Single Account 2 (ethereumjs)"
INFO[06-28|21:39:47] API: client ethereumjs started           suite=0 test=4 container=24f77923
INFO[06-28|21:39:59] API: test ended                          suite=0 test=4 pass=true
INFO[06-28|21:39:59] API: test started                        suite=0 test=5 name="Blob Transaction Ordering, Multiple Accounts (ethereumjs)"
INFO[06-28|21:40:02] API: client ethereumjs started           suite=0 test=5 container=c083a8d3
INFO[06-28|21:40:13] API: test ended                          suite=0 test=5 pass=true
INFO[06-28|21:40:13] API: test started                        suite=0 test=6 name="Blob Transaction Ordering, Multiple Clients (ethereumjs)"
INFO[06-28|21:40:16] API: client ethereumjs started           suite=0 test=6 container=1738294e
INFO[06-28|21:40:17] API: container IP requested              network=bridge container=1738294e ip=172.17.0.4
INFO[06-28|21:40:20] API: client ethereumjs started           suite=0 test=6 container=b1a121a3
INFO[06-28|21:41:28] API: test ended                          suite=0 test=6 pass=false
INFO[06-28|21:41:28] API: test started                        suite=0 test=7 name="Replace Blob Transactions (ethereumjs)"
INFO[06-28|21:41:31] API: client ethereumjs started           suite=0 test=7 container=282c39d1
INFO[06-28|21:42:41] API: test ended                          suite=0 test=7 pass=false
INFO[06-28|21:42:41] API: test started                        suite=0 test=8 name="Parallel Blob Transactions (ethereumjs)"
INFO[06-28|21:42:44] API: client ethereumjs started           suite=0 test=8 container=e29decd0
INFO[06-28|21:43:01] API: test ended                          suite=0 test=8 pass=true
INFO[06-28|21:43:01] API: test started                        suite=0 test=9 name="NewPayloadV2 After Cancun (ethereumjs)"
INFO[06-28|21:43:03] API: client ethereumjs started           suite=0 test=9 container=b91f0b97
INFO[06-28|21:43:06] API: test ended                          suite=0 test=9 pass=false
INFO[06-28|21:43:06] API: test started                        suite=0 test=10 name="NewPayloadV3 Before Cancun (ethereumjs)"
INFO[06-28|21:43:08] API: client ethereumjs started           suite=0 test=10 container=6abcdd19
INFO[06-28|21:43:11] API: test ended                          suite=0 test=10 pass=false
INFO[06-28|21:43:11] API: test started                        suite=0 test=11 name="NewPayloadV3 Versioned Hashes, Missing Hash (ethereumjs)"
INFO[06-28|21:43:14] API: client ethereumjs started           suite=0 test=11 container=f10bc3cf
INFO[06-28|21:43:18] API: test ended                          suite=0 test=11 pass=true
INFO[06-28|21:43:18] API: test started                        suite=0 test=12 name="NewPayloadV3 Versioned Hashes, Extra Hash (ethereumjs)"
INFO[06-28|21:43:21] API: client ethereumjs started           suite=0 test=12 container=e92fad4a
INFO[06-28|21:43:25] API: test ended                          suite=0 test=12 pass=true
INFO[06-28|21:43:25] API: test started                        suite=0 test=13 name="NewPayloadV3 Versioned Hashes, Out of Order (ethereumjs)"
INFO[06-28|21:43:28] API: client ethereumjs started           suite=0 test=13 container=c261324e
INFO[06-28|21:43:32] API: test ended                          suite=0 test=13 pass=true
INFO[06-28|21:43:32] API: test started                        suite=0 test=14 name="NewPayloadV3 Versioned Hashes, Repeated Hash (ethereumjs)"
INFO[06-28|21:43:35] API: client ethereumjs started           suite=0 test=14 container=098c795d
INFO[06-28|21:43:39] API: test ended                          suite=0 test=14 pass=true
INFO[06-28|21:43:39] API: test started                        suite=0 test=15 name="NewPayloadV3 Versioned Hashes, Incorrect Hash (ethereumjs)"
INFO[06-28|21:43:42] API: client ethereumjs started           suite=0 test=15 container=460fe2a1
INFO[06-28|21:43:46] API: test ended                          suite=0 test=15 pass=true
INFO[06-28|21:43:46] API: test started                        suite=0 test=16 name="NewPayloadV3 Versioned Hashes, Incorrect Version (ethereumjs)"
INFO[06-28|21:43:49] API: client ethereumjs started           suite=0 test=16 container=4bfbee56
INFO[06-28|21:43:53] API: test ended                          suite=0 test=16 pass=true
INFO[06-28|21:43:53] API: test started                        suite=0 test=17 name="NewPayloadV3 Versioned Hashes, Nil Hashes (ethereumjs)"
INFO[06-28|21:43:55] API: client ethereumjs started           suite=0 test=17 container=8b28aec5
INFO[06-28|21:43:58] API: test ended                          suite=0 test=17 pass=false
INFO[06-28|21:43:58] API: test started                        suite=0 test=18 name="NewPayloadV3 Versioned Hashes, Empty Hashes (ethereumjs)"
INFO[06-28|21:44:01] API: client ethereumjs started           suite=0 test=18 container=662d9da5
INFO[06-28|21:44:05] API: test ended                          suite=0 test=18 pass=true
INFO[06-28|21:44:05] API: test started                        suite=0 test=19 name="NewPayloadV3 Versioned Hashes, Non-Empty Hashes (ethereumjs)"
INFO[06-28|21:44:08] API: client ethereumjs started           suite=0 test=19 container=43ff7257
INFO[06-28|21:44:12] API: test ended                          suite=0 test=19 pass=true
INFO[06-28|21:44:12] API: test started                        suite=0 test=20 name="NewPayloadV3 Versioned Hashes, Missing Hash (Syncing) (ethereumjs)"
INFO[06-28|21:44:15] API: client ethereumjs started           suite=0 test=20 container=1a9dad21
INFO[06-28|21:44:21] API: client ethereumjs started           suite=0 test=20 container=6e6813ed
INFO[06-28|21:44:23] API: test ended                          suite=0 test=20 pass=true
INFO[06-28|21:44:23] API: test started                        suite=0 test=21 name="NewPayloadV3 Versioned Hashes, Extra Hash (Syncing) (ethereumjs)"
INFO[06-28|21:44:26] API: client ethereumjs started           suite=0 test=21 container=17a22ff4
INFO[06-28|21:44:33] API: client ethereumjs started           suite=0 test=21 container=eaa1a85c
INFO[06-28|21:44:35] API: test ended                          suite=0 test=21 pass=true
INFO[06-28|21:44:35] API: test started                        suite=0 test=22 name="NewPayloadV3 Versioned Hashes, Out of Order (Syncing) (ethereumjs)"
INFO[06-28|21:44:38] API: client ethereumjs started           suite=0 test=22 container=5c7247be
INFO[06-28|21:44:44] API: client ethereumjs started           suite=0 test=22 container=bdd023c3
INFO[06-28|21:44:46] API: test ended                          suite=0 test=22 pass=true
INFO[06-28|21:44:46] API: test started                        suite=0 test=23 name="NewPayloadV3 Versioned Hashes, Repeated Hash (Syncing) (ethereumjs)"
INFO[06-28|21:44:49] API: client ethereumjs started           suite=0 test=23 container=f51b2676
INFO[06-28|21:44:56] API: client ethereumjs started           suite=0 test=23 container=c3536aa4
INFO[06-28|21:44:57] API: test ended                          suite=0 test=23 pass=true
INFO[06-28|21:44:57] API: test started                        suite=0 test=24 name="NewPayloadV3 Versioned Hashes, Incorrect Hash (Syncing) (ethereumjs)"
INFO[06-28|21:45:00] API: client ethereumjs started           suite=0 test=24 container=ed18a2b3
INFO[06-28|21:45:07] API: client ethereumjs started           suite=0 test=24 container=ee2259b6
INFO[06-28|21:45:09] API: test ended                          suite=0 test=24 pass=true
INFO[06-28|21:45:09] API: test started                        suite=0 test=25 name="NewPayloadV3 Versioned Hashes, Incorrect Version (Syncing) (ethereumjs)"
INFO[06-28|21:45:12] API: client ethereumjs started           suite=0 test=25 container=41c852ac
INFO[06-28|21:45:19] API: client ethereumjs started           suite=0 test=25 container=87f3f6e9
INFO[06-28|21:45:20] API: test ended                          suite=0 test=25 pass=true
INFO[06-28|21:45:20] API: test started                        suite=0 test=26 name="NewPayloadV3 Versioned Hashes, Nil Hashes (Syncing) (ethereumjs)"
INFO[06-28|21:45:23] API: client ethereumjs started           suite=0 test=26 container=d1341b53
INFO[06-28|21:45:30] API: client ethereumjs started           suite=0 test=26 container=563e54b6
INFO[06-28|21:45:30] API: test ended                          suite=0 test=26 pass=false
INFO[06-28|21:45:30] API: test started                        suite=0 test=27 name="NewPayloadV3 Versioned Hashes, Empty Hashes (Syncing) (ethereumjs)"
INFO[06-28|21:45:33] API: client ethereumjs started           suite=0 test=27 container=8e97686b
INFO[06-28|21:45:40] API: client ethereumjs started           suite=0 test=27 container=ab49454d
INFO[06-28|21:45:42] API: test ended                          suite=0 test=27 pass=true
INFO[06-28|21:45:42] API: test started                        suite=0 test=28 name="NewPayloadV3 Versioned Hashes, Non-Empty Hashes (Syncing) (ethereumjs)"
INFO[06-28|21:45:45] API: client ethereumjs started           suite=0 test=28 container=1bfa861d
INFO[06-28|21:45:50] API: client ethereumjs started           suite=0 test=28 container=52f0c107
INFO[06-28|21:45:52] API: test ended                          suite=0 test=28 pass=true
INFO[06-28|21:45:52] API: test started                        suite=0 test=29 name="Incorrect DataGasUsed: Non-Zero on Zero Blobs (ethereumjs)"
INFO[06-28|21:45:55] API: client ethereumjs started           suite=0 test=29 container=c1ce3595
INFO[06-28|21:45:59] API: test ended                          suite=0 test=29 pass=true
INFO[06-28|21:45:59] API: test started                        suite=0 test=30 name="Incorrect DataGasUsed: DATA_GAS_PER_BLOB on Zero Blobs (ethereumjs)"
INFO[06-28|21:46:01] API: client ethereumjs started           suite=0 test=30 container=eafb6703
INFO[06-28|21:46:05] API: test ended                          suite=0 test=30 pass=true
INFO[06-28|21:46:06] API: suite ended                         suite=0
INFO[06-28|21:46:06] simulation ethereum/engine finished      suites=1 tests=30 failed=6
6 tests failed
```

Failing:

```
Blob Transaction Ordering, Multiple Clients
Replace Blob Transactions
NewPayloadV2 After Cancun (ethereumjs)
NewPayloadV3 Before Cancun (ethereumjs)
NewPayloadV3 Versioned Hashes, Nil Hashes (ethereumjs)
NewPayloadV3 Versioned Hashes, Nil Hashes (Syncing) (ethereumjs)
```

### PR DESCRIPTION
**Pull request by jochem-brouwer**
Closes #2838

Addresses failing hive tests.

To run: **TODO**

### CODE REVIEW

**Review by acolytec3 — COMMENTED** [review]
Is this PR still valid given #2896?

**Comment by jochem-brouwer** [comment]
I will check, but I think so, since we failed (some) hive tests on devnet7.

**Comment by holgerd77** [comment]
Can this get an update at some point?

Maybe it’s best to cherry-pick remaining valid changes into a new PR?

**Comment by jochem-brouwer** [comment]
This got merged in #2935

**Pull request closed without merging**
