### PR TITLE
StateManager: Do not throw calling `getContractStorage` on non-existing accounts 

### PR DESCRIPTION
**Pull request by jochem-brouwer**
Closes https://github.com/ethereumjs/ethereumjs-monorepo/issues/3479

### CODE REVIEW

**Comment by acolytec3** [comment]
This looks good to me. Should we add a check to test the result here?

**Comment by jochem-brouwer** [comment]
I've added a test! Side-note: I did not have to edit a test, so we did not directly test "getContractStorage throws when called on non-existing account" in the past :thinking:

**Comment by holgerd77** [comment]
What is the status of this PR?

**Comment by jochem-brouwer** [comment]
Ready for review!

**Review by Mikhai56 — APPROVED** [review]

**Pull request merged**
