### PR TITLE
vm: skip `_runStepHook` method if no step event listener

### PR DESCRIPTION
**Pull request by acolytec3**
Adds a check in the `interpreter` to skip the `_runStepHook` function if there are no `step` event listeners since this method's sole purpose is to create and emit the `step` event.  The `step` is only used in tests in our code base so this should produce some (likely minor) overall improvement in VM performance since this function is run on each step in VM execution.

### CODE REVIEW

**Review by holgerd77 — APPROVED** [review]
Looks good, tested this with the following code:

```javascript
import VM from './src'
let vm = new VM()
vm.listenerCount('step') // 0
vm.on('step', () => { console.log('Called step') })
vm.listenerCount('step') // 1
```

This should also be implicitly covered by tests in `tests/api/events.spec.ts`.

Read something about this in the chat but couldn't find any more, so was there actually some impact on performance by this change?

**Comment by holgerd77** [comment]
Argh, this can actually be directly reverted again.

The `_runStepHook` function is actually also used to prepare the output for the `DEBUG` logger, see [here](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/vm/src/evm/interpreter.ts#L193).

Could you guys please have a minimal look into the code base itself before you comment out some stuff? 😐 This is a bit annoying and a bit too sloppy to overlook.

**Comment by jochem-brouwer** [comment]
Argh, sorry this is my fault @holgerd77, I pitched this to @acolytec3 as "low hanging fruit" optimization and did skim over the code to convince myself there were no side effects if we disabled it with no listeners. Clearly I was not careful and did not take enough time to notice there were in fact side effects. My apologies! 😞

**Comment by holgerd77** [comment]
Thanks, no worries, nothing which can't be reverted. Generally a good idea.

Respectively, on looking at the code again: this just seems to need an additional `or` check for `this._vm.DEBUG` in the call-it-or-not switch. 🙂

**Comment by acolytec3** [comment]
Ugh, sorry, that wasn't obvious to me though I wondered about the flag. I'll add another PR tonight to address.

**Pull request merged**
