### PR TITLE
Tx: Ensure TxOptions propagate from unsigned to signed

### PR DESCRIPTION
**Pull request by jochem-brouwer**
When creating a transaction, `TxOptions` do not get propagated from the unsigned tx to the signed tx. I'd say that if one creates an unsigned tx with `{freeze: false}` then one expects that the signed tx is then also frozen (?). The alternative is that we explicitly add this as potentially undefined parameter in `sign`.

WDYT?

### CODE REVIEW

**Comment by holgerd77** [comment]
Yes, I would very much agree here, will likely be also true for additional future options as well (one might need to be careful with creational options though which do something in the constructor like (nonsense example here but just to get the idea) `calcBaseFee` or something like that).

Is this still WIP? I would otherwise be confident to review and merge here I would say.

**Comment by jochem-brouwer** [comment]
I wanted to await some comments on this one but had a discussion with @ryanio on discord and I think he also agreed this is correct (?) so I will mark this as ready for review.

**Comment by jochem-brouwer** [comment]
Thanks for the rebase :smile:

**Comment by ryanio** [comment]
My only comment is that we should not store and use this.txOptions.common since we already have this.common and do not want two sources of truth, since common can be changed with functions like setHardforkByBlock

**Review by ryanio — APPROVED** [review]
lgtm!

**Pull request merged**
