### PR TITLE
VM: Update ethereum/tests to 10.0

### PR DESCRIPTION
**Pull request by jochem-brouwer**

### CODE REVIEW

**Comment by ryanio** [comment]
For reference: https://github.com/ethereum/tests/releases/tag/v10.0

Looks like no failures, the only one in `vm-state (Berlin)` is the count:
`not ok 13066 expected 13156 checks, got 13065`

**Comment by ryanio** [comment]
I also really liked this [test process diagram](http://tinyurl.com/2ctak8yn) linked in the release notes, might be something we can add to `vm/developer.md`  as an overview of the `ethereum/tests` setup. (Note: we should uppercase that file to `DEVELOPER.md` to match our other files and update the link to it in `vm/README.md`)

**Comment by holgerd77** [comment]
> uppercase that file to `DEVELOPER.md` to match our other internal docs files and update the link to it from `vm/README.md`

Have added to tiny-fixes-issue #905.

Not sure if adding the diagram is bringing so much value/insight (though I like myself), at the end we are only using a small extract from currently?

grafik

But absolutely no strong opinion, just to mention.

**Review by holgerd77 — APPROVED** [review]
LGTM, thanks! 😄

**Comment by holgerd77** [comment]
(short note: please remember to use expressive names for the PR titles due to our new "Squash and merge" philosophy)

**Pull request merged**
