### PR TITLE
Common: Remove calaveras ephemerial testnet

### PR DESCRIPTION
**Pull request by Zachinquarantine**
The Calaveras testnet was only used for testing the London upgrade AFAIK, and since the London upgrade has come and gone, this PR removes support for Calaveras.

### CODE REVIEW

**Comment by Zachinquarantine** [comment]
>  but also make sure to always run `npm run lint:fix` before pushing to have your code formatted properly

I get:
npm ERR! Missing script: "lint:fix"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run
What should I do?

**Comment by ryanio** [comment]
> >  but also make sure to always run `npm run lint:fix` before pushing to have your code formatted properly
> 
> 
> 
> I get:
> 
> npm ERR! Missing script: "lint:fix"
> 
> npm ERR! 
> 
> npm ERR! To see a list of scripts, run:
> 
> npm ERR!   npm run
> 
> What should I do?

If on root run with `--workspaces` to run the cmd in all packages.

So: `npm run lint:fix --workspaces`

**Comment by Zachinquarantine** [comment]
> 
> 
> > > but also make sure to always run `npm run lint:fix` before pushing to have your code formatted properly
> > 
> > 
> > I get:
> > npm ERR! Missing script: "lint:fix"
> > npm ERR!
> > npm ERR! To see a list of scripts, run:
> > npm ERR!   npm run
> > What should I do?
> 
> If on root run with `--workspaces` to run the cmd in all packages.
> 
> So: `npm run lint:fix --workspaces`

I don't think I have ``lint`` installed at all, how can I install it?

**Comment by holgerd77** [comment]
@Zachinquarantine you need to one-time run `npm i` from the root of your monorepo to install all dependencies and dev dependencies and build all the packages (takes a couple of minutes).

**Comment by acolytec3** [comment]
This looks good!  Looks like everything is cleaned up and tests are all passing.  @holgerd77 I think this is technically a breaking change on `common` so will defer to your judgement on when/how to merge.

**Comment by holgerd77** [comment]
@acolytec3 after sleeping on this one night I am actually even more confident that we just can merge this into `master` and actually also continue with our current practice on adding (and removing) these testnets to `Common`.

People very well know that these testnets are just temporary and I guess the chance that someone is hardcoding a reference to these testnets into a production library is extremely rare.

So @Zachinquarantine thanks again for the contribution, will merge.

**Review by holgerd77 — APPROVED** [review]
LGTM

**Pull request merged**
