### PR TITLE
client: decouple skeleton from beacon sync

### PR DESCRIPTION
**Pull request by g11tech**
skeleton needs to be shared between beacon sync and snap sync to keep the engine api working as well as to keep updating snapsync with latest stateroot.

this PR decouples skeleon from beacon sync

### CODE REVIEW

**Comment by holgerd77** [comment]
Updated this via UI

**Comment by acolytec3** [comment]
I updates a fair amount of the typing in the tests that were changed.  Looks good overall but would be nice to finish cleaning up the typing in the tests before we merge.

**Comment by g11tech** [comment]
@acolytec3  i could do separate PR for increasing the typing of the sim utils as followup

**Review by acolytec3 — APPROVED** [review]
LGTM

**Comment by holgerd77** [comment]
Still wonder if we could (and would want to) transfer skeleton to become a sub entity or similar of Blockchain? 🤔

**Pull request merged**
