### PR TITLE
Implement EIP3074: AUTHCALL

### PR DESCRIPTION
**Pull request by jochem-brouwer**
Implements https://eips.ethereum.org/EIPS/eip-3074

### CODE REVIEW

**Comment by ryanio** [comment]
if there is no urgency to get this in a vm v5 release, then i wonder if we should target develop (vm v6) so we don't have to refactor the code from BN to bigint again

**Comment by jochem-brouwer** [comment]
There is no urgency, will target `develop`

**Comment by jochem-brouwer** [comment]
Right, before I continue should first rebase on develop.

**Comment by jochem-brouwer** [comment]
Closed in favor of #1789

**Comment by holgerd77** [comment]
> if there is no urgency to get this in a vm v5 release, then i wonder if we should target develop (vm v6) so we don't have to refactor the code from BN to bigint again

Yes, that makes a dramatic amount of sense 😜, hadn't thought about that either yet but we can very well start to do so. This will take some time to implement anyhow on these new bigger tasks, and v6 is finally not *that* far away any more (2-3 months I would say).

**Pull request closed without merging**
