### PR TITLE
client: Multifetcher synchronizer support

### LINKED ISSUE #2389: Modify Synchronizer class to support multi-fetcher syncs
Currently, in order to run a fetcher, the `fetcher` field of a `Synchronizer` object has to be set to a `Fetcher` object that has been initialized. This creates a one-to-one relationship between the `Synchronizer` and `Fetcher` classes. For snap sync, it is necessary to create and run many fetchers - specifically, four (storage, account, bytecode, and trie node). Modify the `Synchronizer` class to accept an array of fetchers. It can call the `fetch` method of each, and resolve only when all fetchers are done fetching.

Also see #2345

### PR DESCRIPTION
**Pull request by scorbajio**
Fixes #2389.

### CODE REVIEW

**Review by g11tech — CHANGES_REQUESTED** [review]
I would not extend the fetcher to be fetches, but the better solution will be to have snap's own fetcher that might span their own fetchers, and idealy that should be handled in job creation and not multiple fechers.

**Comment by scorbajio** [comment]
> I would not extend the fetcher to be fetches, but the better solution will be to have snap's own fetcher that might span their own fetchers, and idealy that should be handled in job creation and not multiple fechers.

I don't understand the part where you say "that should be handled in job creation and not multiple fetchers." Can you give a full explanation of the alternative solution that you are proposing and explain what makes it better?

**Comment by holgerd77** [comment]
> I would not extend the fetcher to be fetches, but the better solution will be to have snap's own fetcher that might span their own fetchers, and idealy that should be handled in job creation and not multiple fechers.

@g11tech Yeah, I would agree with @scorbajio here, could you please give a reasoning for the alternative design suggestion? What would be the shortcomings respectively what are the strucural advantages of the proposed alternative? 🙂

**Comment by g11tech** [comment]
> > I would not extend the fetcher to be fetches, but the better solution will be to have snap's own fetcher that might span their own fetchers, and idealy that should be handled in job creation and not multiple fechers.
> 
> @g11tech Yeah, I would agree with @scorbajio here, could you please give a reasoning for the alternative design suggestion? What would be the shortcomings respectively what are the strucural advantages of the proposed alternative? slightly_smiling_face

There should be an "umberalla" snapfetcher that houses all the fetchers related to snap, current PR really introduces a  possible dangerous mix of fetchers from across synchronizers and might really introduce hard to find bugs

Also the contribution of this PR is to add fetchers array without adding how they will be used in snap. I am not conviced of this design but @scorbajio can certainly use it to prototype. This is however not merge-able/worthy  in the current state (in my opinion).

When a client actually runs, it becomes very hard to reason why something is happening as sync is primarily very hard in my opinion. So unless there is a very convincing reason this is how it should be done, it would be better to not have array over here (and also not an unbounded array inside the snapfetcher)

**Comment by holgerd77** [comment]
What is the state of this?

**Comment by g11tech** [comment]
closing this in favour of the nested fetcher designed as merged in https://github.com/ethereumjs/ethereumjs-monorepo/pull/2345

**Pull request closed without merging**
