### PR TITLE
EIP 6110 fixes

### PR DESCRIPTION
**Pull request by jochem-brouwer**
This PR runs these 6110 tests: https://github.com/ethereum/execution-spec-tests/files/15101579/fixtures_develop.tar.gz

(only activate 6110 and 7685 in common)

### CODE REVIEW

**Comment by acolytec3** [comment]
That's a promising start!

**Comment by acolytec3** [comment]
I wonder if we're not encoding the other 3 fields correctly (e.g. they're BE in the event but should be LE in the request)?

**Comment by jochem-brouwer** [comment]
I just fixed it, all tests now pass! For some reason extracting LE Uint64 using DataView did not work, so I settled on this by manually converting the LEs to BEs.

**Comment by acolytec3** [comment]
Just need to adjust the error message the test checks for and this will be ready to merge

**Review by acolytec3 — APPROVED** [review]
LGTM

**Review by scorbajio — APPROVED** [review]
LGTM

**Pull request merged**
