### PR TITLE
block: swap withdrawal/opts in constructor

### PR DESCRIPTION
**Pull request by jochem-brouwer**
Not a super big deal in retrospect since we point users to use our static methods instead of using the constructor directly.

### CODE REVIEW

**Comment by jochem-brouwer** [comment]
Very sloppy of me, will address tomorrow.

**Comment by holgerd77** [comment]
Did a branch update here via UI

**Comment by holgerd77** [comment]
Did a branch update here via UI

**Review by acolytec3 — APPROVED** [review]
LGTM!

**Review by acolytec3 — APPROVED** [review]
LGTM!

**Comment by g11tech** [comment]
looks good, checked post merge!

**Pull request merged**
