### PR TITLE
evm: move map -> array for opcodes/gas

### PR DESCRIPTION
**Pull request by jochem-brouwer**
This PR changes the internal Opcodes / Dynamic Gas type from Map -> Array. Array lookups seem faster than Map.

Also super small code cleanup, such as removing unused arguments (`_common`)

### CODE REVIEW

**Comment by holgerd77** [comment]
I add blocked/do-not-merge labels so that this does not get accidentally merged.

For context see #work channel discussion.

**Comment by jochem-brouwer** [comment]
Ah right, sorry, should have done that also. Thanks for adding :smile: :+1:

**Comment by jochem-brouwer** [comment]
Have also marked as draft!

**Comment by holgerd77** [comment]
I think we might want to close here and not act upon this?

**Comment by jochem-brouwer** [comment]
Yep!

**Pull request closed without merging**
