### PR TITLE
v5-maintenance--vm-copy-bug

### PR DESCRIPTION
**Pull request by ScottyPoi**
Fixes for #2017 on master

User found a bug in vm.copy(). Options such as allowsUnlimitedContractSize were not being passed on to the copy.

Fixed by editing the VM.create({...}) call in VM.copy() to specifically include these options.

### CODE REVIEW

**Review by holgerd77 — DISMISSED** [review]
Ah, this looks actually pretty good, cool cool! 😄 👍 

Will merge.

**Comment by holgerd77** [comment]
Ah, respectively: there is CI test failure here in the VM api test, so cannot merge yet.

This very much seems to be unrelated though, Chrome browser tests are failing? 🤔

Unfortunately no time to further dig into this.

**Comment by ScottyPoi** [comment]
@holgerd77 
just a typo -- should be good now

**Review by g11tech — APPROVED** [review]
LGTM!

**Pull request merged**
