### PR TITLE
common: set the default hard fork to merge

### LINKED ISSUE #2015: Monorepo: Make Merge Default Hardfork
Since we are now getting so close to the Merge HF date with our breaking releases (or might be even do *after* the Merge, we'll see) I would be a big fan of directly making the Merge HF the default HF on the libraries.

There would be a very very tiny window of where we are "ahead" (and even this wouldn't be bad), and otherwise we would be aligned with the current HF during very much most of the time of the release lifecycle. 🙂 

Inspiration and guidance for update locations can be taken from the London HF work #1749 done by @emersonmacro. I would be very much expecting though that this upgrade work is not as extensive any more (but still some work to do), since Emmett hardened e.g. various code parts like test initializations along the way (by explicitly providing a certain HF e.g.).

This doesn't need to be finished before Beta 2 but can e.g. be done if someone gets bored while I am and other are on holidays e.g.. 😅

### PR DESCRIPTION
**Pull request by g11tech**
set the default hard fork to merge

Closes #2015

### CODE REVIEW

**Comment by gabrocheleau** [comment]
Looks good! However some merged-related tests are now failing in `merge.spec.ts`:
- 'should mine and stop at the merge (PoA)'
- 'should mine and stop at the merge (PoW)'

Didn't check in detail but perhaps all that's required is to manually provide a pre-merge HF for those test cases

**Comment by g11tech** [comment]
thanks @acolytec3 for fixes, got distracted after pushing initial PR :wink:

**Review by gabrocheleau — DISMISSED** [review]
LGTM! 👍🏼

**Review by gabrocheleau — APPROVED** [review]

**Comment by holgerd77** [comment]
Nice, cool, didn't assume this to be so narrowly scoped respectively going through with so few changes. 😀 🤩 Seems Emmett already did a lot of base work here with adding the explicit HF (Common) instantiations in the round before upgrading to London.

Great!

**Pull request merged**
