### PR TITLE
verkle: add verkle-trie package

### PR DESCRIPTION
**Pull request by gabrocheleau**

### CODE REVIEW

**Comment by holgerd77** [comment]
This can now be closed, right?

**Comment by gabrocheleau** [comment]
Technically no, since this is a new thing (refactoring kev's verkle-trie-js package), but I'll close and create a new one regardless as it's going to be cleaner anyway.

**Comment by holgerd77** [comment]
Ah, ok 🤯, again this naming confusion, I thought this would refer to our own package and therefore be redundant.

**Comment by gabrocheleau** [comment]
> Ah, ok 🤯, again this naming confusion, I thought this would refer to our own package and therefore be redundant.

Yeah agreed, will bring this up to kev

**Pull request closed without merging**
