### PR TITLE
Fix bug in how precompiles activated by EIP are identified

### PR DESCRIPTION
**Pull request by acolytec3**
Fixes a bug in the EVM where precompiles that are activated by EIP might not be activated if their trigger EIP is activated on a hardfork rather than by passing an EIP into the `common` constructor.  Was discovered while working on 4844.

### CODE REVIEW

**Comment by jochem-brouwer** [comment]
Ah right looks good to me. Maybe add a test?

**Review by holgerd77 — DISMISSED** [review]
I'll give this a go here also without an additional test case, I guess at the moment we should prioritize getting our code base ready and updated.

Test case would be nice, but this is also very much implicitly tested by precompile calling, and when the PR then additionally fixes stuff in the 4844 branch it is basically "proven" [TM] that the status quo has been improved by this.

**Comment by acolytec3** [comment]
Could I get another approval on this one? The actual change in the EVM was also included in the 4844 PR but we should still move these 2537 tests over to the `evm` folder so would like to go ahead and merge this.

**Review by g11tech — APPROVED** [review]
lgtm

**Pull request merged**
