### PR TITLE
MPT: New Release v4.1.0

### PR DESCRIPTION
**Pull request by holgerd77**
MPT release with the new checkpointing mechanism and other CI and docs related changes (see CHANGELOG).

Please notice that I reverted a `Trie.setRoot()` -> `Trie._setRoot()` rename (introduced by myself) from https://github.com/ethereumjs/merkle-patricia-tree/pull/125 and switched to deprecating instead. This seemed to dangerous to me on retrospective regarding introducing a breaking change. Have instead added to #1024.

### CODE REVIEW

**Review by cgewecke — APPROVED** [review]
Looks good 💯

**Review by ryanio — APPROVED** [review]
lgtm!

**Comment by holgerd77** [comment]
Already reviewed and just updated the branch on tiny changes, will admin-merge for practical reasons.

**Comment by holgerd77** [comment]
Just released this as [v4.1.0](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/merkle-patricia-tree%404.1.0) on npm.

**Pull request merged**
