### PR TITLE
Reintegrate Skipped vm Tests

### PR DESCRIPTION
**Pull request by scorbajio**
See #2929.

### CODE REVIEW

**Comment by scorbajio** [comment]
It seems like the following tests are not being discovered:
```
  'ackermann',
  'fibonacci',
  'loop-add-10M',
  'loop-divadd-10M',
  'loop-divadd-unr100-10M',
  'loop-exp',
  'loop-mul',
  'manyFunctions100',
  'randomStatetest94_Istanbul',
  'static_Callcode50000',
  'static_Return50000',
  'Call50000bytesContract50_1',
  'Call50000bytesContract50_2',
```
They can potentially be removed since they don't exist.

**Review by jochem-brouwer — APPROVED** [review]
LGTM, thanks!

**Comment by jochem-brouwer** [comment]
Shanghai is fast enough for the newly added tests (added tests <2s)

I was also interested in the other forks, some results:

```
2023-08-03T20:59:55.1827975Z # file: GeneralStateTests/stQuadraticComplexityTest/QuadraticComplexitySolidity_CallDataCopy_d0g1v0.json test: QuadraticComplexitySolidity_CallDataCopy_d0g1v0_Constantinople
2023-08-03T20:59:55.1834591Z ok 6103 correct genesis RLP
2023-08-03T20:59:55.1855017Z ok 6104 correct pre stateRoot
2023-08-03T21:00:59.5882898Z ok 6105 correct last header block
2023-08-03T21:00:59.5884351Z # Time: 64.405 secs
```

```
2023-08-03T21:03:38.7509315Z # file: GeneralStateTests/stQuadraticComplexityTest/QuadraticComplexitySolidity_CallDataCopy_d0g1v0.json test: QuadraticComplexitySolidity_CallDataCopy_d0g1v0_ConstantinopleFix
2023-08-03T21:03:38.7516140Z ok 6100 correct genesis RLP
2023-08-03T21:03:38.7537776Z ok 6101 correct pre stateRoot
2023-08-03T21:04:56.1089781Z ok 6102 correct last header block
2023-08-03T21:04:56.1093329Z # Time: 77.357 secs
```

Very interesting to see (but these are super old forks so we should not pay attention to this at this point)

**Comment by holgerd77** [comment]
@jochem-brouwer yeah, but we need to pay attention to old forks at least to the point that this is not "breaking" our all-forks-test-runs with this extra GitHub label (so by running too long or even crashing).

**Pull request merged**
