### PR TITLE
monorepo: rename versionedHashes -> blobVersionedHashes

### PR DESCRIPTION
**Pull request by jochem-brouwer**
Fixes hive tests, hive tests (and other clients) expect json fields `blobVersionedHashes` instead of `versionedHashes`, see also: 

https://github.com/ethereum/execution-apis/blob/b2002ee23166c2b4a75c39cc36f6c9a04890920f/src/schemas/transaction.yaml#L51

Not sure if CI passes

### CODE REVIEW

**Comment by g11tech** [comment]
looks good, i think some renaming issue in the browser tests?

**Comment by jochem-brouwer** [comment]
Not super sure why the browser tests failed but renaming the file worked :thinking:

**Review by g11tech — DISMISSED** [review]
lgtm

**Review by acolytec3 — APPROVED** [review]
LGTM

**Review by g11tech — APPROVED** [review]

**Pull request merged**
