### PR TITLE
refactor(trie): remove unnecessary temp variables and buffer creation

### PR DESCRIPTION
**Pull request by faustbrian**
Removes unnecessary calls to `Buffer.from` and also some temporary variables that seem unnecessary

### CODE REVIEW

**Comment by acolytec3** [comment]
> @acolytec3 should we add a retry trigger to the workflows of the client tests that try to sync?

I didn't realize there was an automatic one but if we could do it for that specific job, that would be excellent.

**Comment by acolytec3** [comment]
> @acolytec3 https://github.com/ethereumjs/ethereumjs-monorepo/runs/7689346278?check_suite_focus=true retry job works. took 2 tries there and passed.

Thanks for the DX improvement!

**Comment by holgerd77** [comment]
Currently in the process of merging/updating other PRs, is this PR imminent to be merged respectively reviewed (@acolytec3)? Then I would wait a bit, don't want to force you guys into yet another branch-update-approval round.

**Review by acolytec3 — APPROVED** [review]
Looks great, thanks!

**Comment by acolytec3** [comment]
> Currently in the process of merging/updating other PRs, is this PR imminent to be merged respectively reviewed (@acolytec3)? Then I would wait a bit, don't want to force you guys into yet another branch-update-approval round.

Yup, done.  Small but excellent PR.  We should consider reviewing this sort of thing across the monorepo

**Pull request merged**
