### PR TITLE
New Tx v3.1.1 Release

### PR DESCRIPTION
**Pull request by holgerd77**
Fixes https://github.com/ethereumjs/ethereumjs-monorepo/issues/1161

I would not do releases on the upstream libraries again, I guess if we are quick here this should be ok.

### CODE REVIEW

**Comment by holgerd77** [comment]
(if anyone find issues on review, please push directly)

**Comment by holgerd77** [comment]
Or would you guys prefer the suggested fix from #1161 ?

**Review by cgewecke — APPROVED** [review]
Super weird bug...will casing definitely be ok with this change? What is causing TS to mess this up?

**Comment by cgewecke** [comment]
Ok sorry - I see you checked the dist locally in #1161. 

Doesn't look like the E2E caught this... maybe if the build/publish happens on linux there's no capitalization.

**Comment by holgerd77** [comment]
@cgewecke thanks for approving, yes, did a few more checks, pretty sure this is ok now. Ok, then I'll directly do the release before this is distributed more broadly.

**Comment by holgerd77** [comment]
(will wait for the tests though of course)

**Comment by cgewecke** [comment]
Closing in favor #1163

**Pull request closed without merging**
