### PR TITLE
Trie: Debug logging

### PR DESCRIPTION
**Pull request by ScottyPoi**
This introduces `debug` logging to the `Trie` class.

Like other packages, all `debug` calls will be wrapped inside of a conditional:
`if (this.DEBUG) { ... } `

`this.DEBUG` will be set to `true` only if the `ethjs` flag has been set in `process.env.DEBUG`

If active, the debugger will log with the namespace: `ethjs:Trie:`

The debugger is available by calling `this.debug(message: string, namespaces: string[])`

`trie.debug()`  will take 1 or 2 parameters.  The first being the string to be logged, the second being a list of added namespaces for that specific message.

So calling `trie.debug('Trie Created')`  will log 
> // **ethjs:trie:**  Trie Created

And calling `trie.debug('Adding value for key: 0xabcd', ['PUT'] )`  will log:
> // **ethjs:trie:PUT** Adding value for key: 0xabcd

----

Also included is `test/util/log.spec.ts`

This runs a minimal trie script with `this.DEBUG` set to true.
The debugger will remain inactive, but `coverage` will touch the code inside of the DEBUG conditionals.
This way the added lines of code for logging do not artificially hurt the `coverage` statistic.

### CODE REVIEW

**Comment by ScottyPoi** [comment]
[trieLogs.pdf](https://github.com/ethereumjs/ethereumjs-monorepo/files/12555032/trieLogs.pdf)

**Comment by holgerd77** [comment]
Thanks a lot, this looks already pretty great! 🤩

What is actually a good and easy way to test (and see) the debug logger?

The following does not yet work: `DEBUG=ethjs,trie:* npm run test:node` while an analogue test on statemanager does.

Didn't have such a close look yet, but this example above is actually following our standard naming pattern for debug logging. So if this is not yet working this should be aligned.

Also, please add a quick README docs section like e.g. for blockchain:
https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/blockchain#developer

**Comment by holgerd77** [comment]
Ah, ok, got it, you took the namespace `ethjs:trie:*`. Yeah, that should be updated to the `ethjs,trie:*` version, since this otherwise don't matches the other libraries.

Decision to have this comma-version was I think to have things shorter when activating several dedicated debuggers from the same library (e.g. `ethjs,devp2p:rlpx:*,devp2p:eth:*`, something like that).

And so we should keep this consistent over the libs.

**Comment by holgerd77** [comment]
Updated this via UI

**Comment by holgerd77** [comment]
Updated this via UI

**Review by holgerd77 — APPROVED** [review]
Very cool, great PR and docs 🤩! Will merge.

**Pull request merged**
