### PR TITLE
Fix statemanager empty code bug

### PR DESCRIPTION
**Pull request by jochem-brouwer**
This PR fixes a bug in StateManager where empty code is put on an account which already has code. This did not `modifyAccountFields` before, which invalidates the cache.

Note: built on top of 7702 see #3470.

### CODE REVIEW

**Review by acolytec3 — DISMISSED** [review]
LGTM

**Comment by jochem-brouwer** [comment]
Re-approve and merge? :smile:

**Review by holgerd77 — APPROVED** [review]
LGTM

**Comment by holgerd77** [comment]
There are still so many commits shown in this PR, is this normal? 🤔

**Comment by holgerd77** [comment]
Shouldn't these go away once the base changes?

**Comment by holgerd77** [comment]
Ok, I'll do it. Should hopefully be ok, changes shown also only show the small diff set.

**Comment by jochem-brouwer** [comment]
Sorry, missed those comments. Squash and merge should do it in the end right? Maybe when I merged 7702 into this one it might have messed up the git commit history :thinking:

**Pull request merged**
