### PR TITLE
client: snap protocol tests

### PR DESCRIPTION
**Pull request by scorbajio**
This PR adds tests for `snapprotocol` and `snapsync`.

### CODE REVIEW

**Review by g11tech — CHANGES_REQUESTED** [review]
@scorbajio i would love to see some logs of the other type of requests, and then encoding/decoding compared against some actual sample.

**Comment by scorbajio** [comment]
> @scorbajio i would love to see some logs of the other requests, and then encoding/decoding compared against some actual sample. Right now using our conver encoder => decoder sort of is self reinforcing, so would be awesome to test them against some actual sample data received from a geth/nethermind or other snap capable peer.

I'm not sure I understand what sample data you're referring to for testing encoding/decoding. Could you explain or give an example?

**Comment by g11tech** [comment]
> > @scorbajio i would love to see some logs of the other requests, and then encoding/decoding compared against some actual sample. Right now using our conver encoder => decoder sort of is self reinforcing, so would be awesome to test them against some actual sample data received from a geth/nethermind or other snap capable peer.
> 
> I'm not sure I understand what sample data you're referring to for testing encoding/decoding. Could you explain or give an example?

ok, i will add the same on top of these tests, for now we can merge these ones

**Review by g11tech — APPROVED** [review]
LGTM! will add more tests on top regarding encoding decoding with real data

**Pull request merged**
