### PR TITLE
VM, Common: updated EIP checks / added EIP-2565, EIP-2929 to Berlin HF

### PR DESCRIPTION
**Pull request by holgerd77**
This PR is to get an in-between overview on where we are with the berlin test runs - still excluding EIP-2718 and EIP-2930 - PR is branched off from #1124.

@jochem-brouwer feel free to merge this one in if useful or we can otherwise merge post #1124 merge, as you like.

### CODE REVIEW

**Comment by jochem-brouwer** [comment]
Very disappointing to see that there are so many tests failing. Will merge.

**Comment by jochem-brouwer** [comment]
Thanks Holger! 😄

**Comment by holgerd77** [comment]
I would assume that there is something still very basic wrong, maybe even just the HF setup, no need to panic or something (yet, hehe 😜 ).

We'll see.

**Comment by holgerd77** [comment]
I did an isolated run of a single test with `DEBUG=vm:*,vm:*:*,-vm:ops:* ts-node ./tests/tester --state --test='invalidAddr' --data=0 --gas=0 --value=0 --fork=Berlin` and compared the results from `Berlin` (failing)  and `Istanbul` (passing).

State root is expected to be different in the test file but when run through the VM state root (as well as the whole execution flow) keeps the same both run on `Istanbul` and `Berlin`.

Not sure what EIP is expected to change the state root here? I've checked, this is not yet in the new transaction format.

**Comment by jochem-brouwer** [comment]
What does this do again? It seems that this only runs tests where data/gas/value is 0? (Maybe this filter is implemented wrong).

I just found a bug (which is probably unrelated). Let's continue this discussion on #1124. Am fixing bugs on a per-test basis.

**Comment by holgerd77** [comment]
Just give a short answer here to one aspect: don't be confused by this data/gas/value selection, this is just selecting the specific test case, nothing else. So if there is a section like this in the test file:

```json
{
                    "indexes" : {
                        "data" : 0,
                        "gas" : 0,
                        "value" : 0
                    },
                    "hash" : "0x012502a75bf4fcefbef2850b492f038ed9863832c6a09e84fc1bce079e33a6f5",
                    "logs" : "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347"
                }
```

These values are just indexes and pointing to the first (0-index) data value in the "transaction" section. So this just a way to run an isolated test case if there are many in one file, nothing else.

**Comment by jochem-brouwer** [comment]
Ah that's interesting, I didn't know what these were in ethereum/tests. Thanks for clarifying. I was actually wondering if we had this feature 😄

**Pull request merged**
